### ISSUE TITLE
ServiceControl is not detecting endpoints based on Audit messages

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceControl#1116]
Steps to Repro:

1. Have a NSB v7 endpoint with auditing setup with no other SC plugins. 
2. Make sure for this endpoint to run and process messages
3. Verify in RavenDB that SC is indeed processing the audit messages
4. However in SP, it does not display any discovered endpoints.

See:
<img width="846" alt="screen shot 2018-03-28 at 8 04 20 pm" src="https://user-images.githubusercontent.com/854553/38067925-51b0795e-32c3-11e8-80c3-60409dab8e86.png">

<img width="553" alt="screen shot 2018-03-28 at 8 04 34 pm" src="https://user-images.githubusercontent.com/854553/38067933-5c1bcbaa-32c3-11e8-962f-c6e4f46a2a92.png">

Versions:
ServicePulse v1.12.0  
ServiceControl v1.47.2

**Comment by WilliamBZA** [comment]
We're in the process of triaging this. No ETA at the moment.

**Comment by tmasternak** [comment]
@indualagarsamy I've tried to reproduce this. What I'm seeing is consistent with your description and expected behavior. 

In other words I don't see the endpoint on the `Endpoints Overview` tab but I do see it in configuration tab.

![image](https://user-images.githubusercontent.com/1092707/38357982-5e3a6c14-38c4-11e8-8bc4-1418f253be31.png)

Can you verify if the endpoint shows up in the configuration tab in your scenario?

**Comment by SzymonPobiega** [comment]
We could not reproduce this behavior while looking up for things to fix in the upcoming ServiceControl/ServicePulse release.
