### ISSUE TITLE
Create scenario for stability test environment

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServiceControl#1135]
Connects to #1130

We need a scenario that places ServiceControl under a repeatable, high load that we can use to capture metrics and monitor the stability of ServiceControl.

**Comment by WilliamBZA** [comment]
Perhaps something along the lines of:

* Seed the database with a set of previous audit messages
* Ingest 1,000,000 audit messages, 250,000 error messages.
* Configure the audit retention period to 1 hour (this will hopefully mean 
* Configure the data cleanup interval to run every minute (`ServiceControl/ExpirationProcessTimerInSeconds`)

While the ingestion process is proceeding, we should trigger batch retry operations - perhaps every 100,000 messages?

This should simulate a large amount of load on the database, as well as forcing ServiceControl to do multiple things at the same time.

**Comment by WilliamBZA** [comment]
We could measure:

* How long it takes to ingest all the messages
* How long it takes to execute the retry operations
* How long each cleanup operation runs for
* How long it takes for each of the error groups to register that new messages are being ingested

**Comment by mikeminutillo** [comment]
Would we put 1m messages into the audit queue and then start up SC or would you start SC and then send 1m messages to it?

If we are loading everything up and then starting SC, that could really make it much easier to handling timing and measuring of everything. We can do it with native queue length tests. i.e. If Retry1 hasn't been sent and the QueueLength of the audit queue is > 100,000, then trigger Retry1. 

Otherwise we need to somehow query SC to get those stats (relying on the API for instance which depends on the underlying indexes).

A straight up Audit test could be:

- Seed the audit queue with 1m messages
- Start a timer
- Start SC
- Time how long until the audit queue starts to go down
- Time how long until the audit queue is empty
- Time how long before the message count from the API reaches 1m

Then we can do something similar with Failed Messages

After that we can introduce some orthogonal concerns like issuing retries, archiving messages, managing retention, handling SI queries, etc.

**Comment by SzymonPobiega** [comment]
I'd start with simple test of loading 1m audit messages while periodically querying the API for the last page.

**Comment by mikeminutillo** [comment]
Agreed. Stability issues are more likely to manifest in more complex scenarios. I'm wondering if we can build a kit of basic tools and compose them.

**Comment by WilliamBZA** [comment]
Ok, so how about this:

### Scenario:

* [ ] Create a docker container with the following
  * SQL Transport
  * A transport database pre-loaded with 1M audit messages
  * A way of measuring and reporting the ingestion progress - Query the SC API as well as the underlying tables and use that to determine when the raven indexes are in sync with reality?
* [ ] Add a similar pre-loaded error queue to the DB
* [ ] Change the image to have pre-ingested messages already in the RavenDB database before starting
  * Measure the impact this has
* [ ] Change the image to have the audit expiration process run whilst importing
  * Measure
* [ ] Add the ability to send RetryGroup messages at repeatable steps through the process

The benefit of using SQL as the transport is that native queue operations are trivial and we can compare the actual committed queue operations with what RavenDB is telling us.

**Comment by WilliamBZA** [comment]
Each of the steps in ☝️ should be able to add value and build on previous steps. At the very least, having a repeatable "it takes X to ingest Y messages and RavenDB seems to cope ok with that" is a good starting metric.

**Comment by WilliamBZA** [comment]
Closing as it seems this is acceptable. Next up: create the scenario
