### ISSUE TITLE
Add mechanism to do previous app.config settings in V7

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServiceControl#1254]

**Comment by danielmarbach** [comment]
Reflected a bit about this and here is a caveat

For example v5 compatible ASB supported [AzureServiceBusQueueConfig](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/support-6.4/src/Transport/Config/AzureServiceBusQueueConfig.cs). A declaration of such a section looks like the following

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <section name="AzureServiceBusQueueConfig"
            type="NServiceBus.Config.AzureServiceBusQueueConfig, NServiceBus.Azure.Transports.WindowsAzureServiceBus" />
    </configSections>

    <AzureServiceBusQueueConfig MaxDeliveryCount="12" />
</configuration>
```
The section name declaration defines the fully qualified assembly name of the config. In order to shim this, we need to rewrite the appearance of the section name to a newly defined section with a similar name in the transport customization assembly. In addition to that, we would need to somehow support all the properties that were provided in that section. 

Maybe it would be better to define a new way to declare settings and then migrate all the v5 supported transport config sections to that new approach directly in one go. Plus custom added sections need to be removed because SC would throw on startup since the assembly containing that section is no longer present in the AppDomain base path.

**Comment by WilliamBZA** [comment]
The fully-qualified name is unfortunate. We could migrate the config and point it to a new config format as part of the upgrade process? I guess if we can't use a strongly typed version of each ConfigSection we could resort to string matching to look for specific properties and extract them manually.

**Comment by WilliamBZA** [comment]
Regular XML parsing to extract the values could also work I suppose

**Comment by WilliamBZA** [comment]
Decision has been made to not support transport specific settings and rather use good defaults going forward.

This makes sense because ServiceControl controls the entire ingestion pipeline and does not need to be configurable to the extend that regular transports need.

**Comment by timbussmann** [comment]
> Decision has been made to not support transport specific settings and rather use good defaults going forward.

to be honest, as this is an RFC I would expect the thoughts and arguments behind this decision being more clearly communicated.
* what's the potential impact on exiting customers?
* what configuration options will no longer be available?
* what are sensible defaults?
* what alternatives have been evaluated?

**Comment by SzymonPobiega** [comment]
@timbussmann 
 
> what's the potential impact on exiting customers

Based on the research we did the impact is minimal as in V7 the transports have much more sensible out-of-the-box settings and don't need that much tuning. 

> what configuration options will no longer be available

 * The ones defined in the Azure transport's configuration sections
 * SQL Server DTC mode (it has never been documented)

> what are sensible defaults

An example is ASB prefetch count. The details (exact values) need to be figured out with cooperation with transport maintainers.

> what alternatives have been evaluated

We considered two options as a replacement for the transport-specific configurations
 * Documenting the transport customization API and allowing users to use their own config packaged in a dll to customize SC
 * Using Transport Adapter

We've selected the Transport Adapter option for now as we believe that in future customizing the transport config should be handled by the core and we want to push in this direction. We can always document the SC-specific transport customization APIs later in SC 3.x era.

**Comment by timbussmann** [comment]
thanks for the info @SzymonPobiega 

The direction seems to make sense, given that we want SC to work out of the box without the need to customize it except for very special edge cases. I don't know enough about the transport adapter to understand what would be required by the user to apply necessary customization though. Do we know how many customers are actually customizing their SC transport settings?

**Comment by SzymonPobiega** [comment]
@timbussmann unfortunately we don't know :-(
