### ISSUE TITLE
Create sensible default configuration for MSMQ

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#1312]
- Check transport for settings that are suitable for concurrent processing of messages that potentially take a few seconds to process
  - Background information: 
    - Audit Ingestion is done with a concurrency of 10, Error Ingestion as well and there is the main input queue of ServiceControl that has a concurrency limit of 10 as well
    - There is also a ReturnToSenderDequeuer that is used when messages are returned to the input queue they came from. More information about that process can be found https://github.com/Particular/ServiceControl/blob/master/docs/bulk-retries-design.md
  - For example, message prefetch should be done cautiously to avoid lock losts or messages getting visible again which can lead to unnecessary dead lettering depending on the transport
  - Other examples are VisibilityTimeout, PeekLock duration...
  - Check what was possible in the v5 version of the transport to influence the transport by providing configuration sections in the App.config, for example ASB had [AzureServiceBusQueueConfig ](https://docs.particular.net/transports/azure-service-bus/configuration/azureservicebusqueueconfig) that allowed to overload the runtime behavior. The idea is that tweaks like that should no longer be needed
- Apply sensible default transport settings in `ServiceControl.Transports.Msmq` assembly both for NSB.Raw and the main input queue
- Determine the best suitable transaction mode for the transport and apply
- If no changes need to be applied please close this issue with a short explanation why the settings are well suited for ServiceControl

**Comment by WilliamBZA** [comment]
The settings that are available:

* DisableInstaller - This is not a setting we want users to be able to change as the queues are installed by SCMU
* DisableDeadLetterQueueing - This should not be disabled to ensure no message loss
* DisableConnectionCachingForSends - 
* UseNonTransactionalQueues - We definitely need transactional queues so do not want anyone to change this value
* EnableJournaling - Since SC is running in prod, this setting should not be used. Raven is essentailly a journal of the messages as well
* TimeToReachQueue - This is not applicable for ServiceControl as retry messages should not have a TTL unless the business endpoint has some business rule around that. Meaning this is not a transport setting that users should have the ability to change for SC
* MSMQ Label - There is no reason for users to have to change this value for SC endpoints.

**Comment by WilliamBZA** [comment]
The only configuration option that I don't have a definitive answer for yet is the `DisableConnectionCachingForSends` setting. This seems like it might be applicable in some scenarios as almost all message retries will be sent to remote machines.

I have asked the MSMQ Maintainers for some input as to when this setting might be useful.

As far as the rest of the settings, there is no reason for users to want to configure them for MSMQ.

**Comment by WilliamBZA** [comment]
It seems this setting is an extremely old setting. I also can't find a support case where this has been proposed as a solution. So I'm going to recommend not allowing this setting to be configurable either.

Closing this issue as there are therefore no configurable requirements for Msmq.
