### ISSUE TITLE
Come up with a way to ensure Web/Message contracts don't change between ServiceControl releases

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServiceControl#1354]
## Overview

* Facilitator: @mauroservienti
* TF Slack channel: https://particularsoftware.slack.com/messages/CCHB3D2D7

ServiceControl currently exposes functionality via 4 channels:

* A RESTful api through NancyFx
* A message-based integration through the [ServiceControl.Contracts Package](https://www.nuget.org/packages/ServiceControl.Contracts/)
* Via messaging internally with itself (This is technically not exposed, but anyone with access can put a message on the ServiceControl queue to invoke that functionality)
* Via SignalR to ServicePulse

Currently there are no mechanisms in place to ensure that the three API surfaces are not changed in a breaking manner between releases.

Focus: Internal benefit and quality assurance

## Proposed PoA

* [x] Confirm that the ServiceControl.Contracts has Particular Approvals running as part of it's build and test
  _Raised https://github.com/Particular/ServiceControl/pull/1421 to start running approval tests_
* [x] Decide if all the internal message classes need to be moved into an assembly so that it can be run against Particular Approvals or if one of the API Builder overloads can be used to determine if the type is an internal message or simply an internal class
  _API Generator allows to select types to generate public API for, no need for a separate assembly_
* [x] Add a test to ensure the internal messages class API doesn't change between releases
  _https://github.com/Particular/ServiceControl/pull/1421 to start running approval tests_
* [x] Decide on a way to generate a text representation of the RESTful API (Swagger? OpenAPI?)
  _we're using the Nancy test infrastructure in https://github.com/Particular/ServiceControl/pull/1421_
* [x] Add a test that compares the test representation of the RESTful API against an approved one
  _https://github.com/Particular/ServiceControl/pull/1421_
* ~Decide on a way to generate a text representation of the SignalR API~
   _We couldn't find any tool to achieve this. We realized it's not needed as we're using 1 single SignalR method (`Broadcast` on the `IConnection` interface) to route all messages from Control to Pulse_
* ~Add a test that compares the test representation of the SignalR API against an approved one~
  _withdrawn_
* [x] raise separate issue related to test Nancy headers https://github.com/Particular/ServiceControl/issues/1431
* [ ] retrospective 

## What you will learn

By joining this taskforce, you will learn:

* Knowledge of API Approvals
* How NancyFx deals with headers and parameter bindings
* SignalR experience

## Required specialists

This taskforce will probably need to have at least some SP and SI maintainers as specialists/reviewers to ensure the full API surface is covered

**Comment by bording** [comment]
Regarding API Approvals, be aware that https://github.com/Particular/Particular.Approvals exists now, and everything should be moving to using it!

**Comment by WilliamBZA** [comment]
Thanks @bording, I've updated the issue

**Comment by boblangley** [comment]
I would like to be considered for the task force on this issue.

**Comment by mauroservienti** [comment]
I’m interested to join this one

**Comment by boblangley** [comment]
As #1367 has launched first, I am now currently unavailable for this issue. However if it still `Needs taskforce` when I am next free I would still be interested in participating.

**Comment by WilliamBZA** [comment]
I've assigned @mauroservienti and will post another announcement again to try find some more members. @Particular/serviceinsight-maintainers @Particular/servicepulse-maintainers Is someone available to act as specialists during review to ensure all API surfaces are covered?

**Comment by mauroservienti** [comment]
I'm leaving this here as a breadcrumb https://github.com/RSuter/SigSpec

**Comment by SzymonPobiega** [comment]
@boblangley @mauroservienti @dvdstelt Ready to roll out?
![Siege Tank](https://static4.fjcdn.com/thumbnails/comments/Spot+on+_ffee0edc20c56efee31f1cbcdb451159.gif)

**Comment by mauroservienti** [comment]
Based on this comment https://github.com/Particular/ServiceControl/issues/1354#issuecomment-415562388 I believe we cannot count on @boblangley for this TF. Should we recruit one more member before kicking this off?

**Comment by SzymonPobiega** [comment]
@mauroservienti #1367 is wrapping up today so I think it should be OK. But let's wait for @boblangley to confirm.

**Comment by boblangley** [comment]
I am ready, willing, and able!

**Comment by mauroservienti** [comment]
TF just had the kick-off meeting, we identified the following areas:

* Identify public types that need to be checked using tools like API Approvals
* Identify public types that DON'T need to be checked using tools like API Approvals, and find the best way to exclude them from the automatic checks
* Investigate how to generate OpenAPI/Swagger-like documentation for Nancy modules
* Investigate how to generate OpenAPI/Swagger-like documentation for SignalR

As of now nothing has to be changed in the PoA.

**Comment by boblangley** [comment]
Nancy research:

ServiceControl currently uses Nancy 1.4.3

https://github.com/yahehe/Nancy.Swagger
- Version 2.1.1 is designed for Nancy v1.4.3 on .Net 4.0+, and creates a Swagger 2.0 document.
- https://github.com/yahehe/Nancy.Swagger/wiki/Standalone-swagger.json-generation

https://github.com/thesheps/nancy.openapi

**Comment by mikeminutillo** [comment]
@boblangley I can act as a reviewer starting on Wednesday

**Comment by mauroservienti** [comment]
Spent some time today with SignalR contract testing or API Approvals, not as easy as I originally thought. The project [linked above](https://github.com/Particular/ServiceControl/issues/1354#issuecomment-415784464) https://github.com/RSuter/SigSpec works with SignalR Core only, and it's actual state is mostly an experiment.

Digging into the ServiceControl solution I don't think that would be a solution in any case. As far as I can tell ServiceControl usage of SignalR is very simple, there are:

* one outgoing channel: `Broadcast` in the `GlobalEventHandler` [class](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Infrastructure/SignalR/GlobalEventHandler.cs)
* one incoming channel, via SignalR message streaming options, in the `MessageStreamerConnection` [class](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Infrastructure/SignalR/MessageStreamerConnection.cs)

Both are very generic and I don't think there is any point in trying to run some sort of API Approvals on those classes. What we should run API Approvals for, though, are the contracts of messages that are exchanged through those channels.

Would be good to isolate them into a separate assembly so that we can easily test their public surface.

@mikeminutillo @boblangley am I missing something?

**Comment by mikeminutillo** [comment]
There is a marker interface for events which will be published down through SignalR. https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Infrastructure/SignalR/IUserInterfaceEvent.cs

I think that the ApiApprovals API can take a `Func<Type, bool>` so it should be easy to filter the list of types without extracting into a separate assembly.

**Comment by mauroservienti** [comment]
Thanks @mikeminutillo. Just for my curiosity, why [`Broadcast`](
https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Infrastructure/SignalR/GlobalEventHandler.cs#L9) takes an object and not that interface?

Any idea on the types that can be sent from the UI to SC via the message stream API?

**Comment by mikeminutillo** [comment]
@mauroservienti 

The interface was added later so it's possible that it was just missed.

AFAIK there are no messages sent from Pulse to Control via the Message Stream API.

**Comment by boblangley** [comment]
@mikeminutillo thanks

@mauroservienti I didn't get back to this today, but tomorrow I will be on it. I agree, just testing the message types should be good enough for SignalR. I like Mike's suggestion for the approach using the Func in the approval tests over separating into another assembly.

**Comment by mauroservienti** [comment]
ServiceControl to talk to Pulse via SignalR uses the `ServicePulseNotifier` class, that handles `IDomainEvent` and only if this event is a `IUserInterfaceEvent` it calls the `Broadcast` method using the `GlobalEventHandler` instance. If I change `Broadcast` to accept only `IUserInterfaceEvent` types instead of object the build is red because `Broadcast` is used also by the `AuditEventLogWriter` that `EventLogItemAdded` to the Pulse UI.

Raised https://github.com/Particular/ServiceControl/pull/1401

The `MessageStreamerConnection` seems to have a double face. It's used by `GlobalEventHandler` to broadcast events to all SP clients connected. And at the same time can receive SignalR messages that are magically converted into messages on a bus. If this second usage is never used, and my interpretation is correct, we should drop the [`OnReceive` method](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Infrastructure/SignalR/MessageStreamerConnection.cs#L31-L54).

Not sure what to do about this last comment.

**Comment by mauroservienti** [comment]
Updated the PoA with recent changes. Please, @boblangley @dvdstelt amend as needed.

**Comment by mauroservienti** [comment]
Heads up: I'll be off the whole week next week (ExploreDDD in Denver)

**Comment by boblangley** [comment]
## Status Update

WIP PR is progressing. Now I am slowly fixing issues with acceptance testing. All but SQS, ASBS, and Learning transports are passing.

**Comment by boblangley** [comment]
## Status PR

- All tests except ASBS passing after rebasing PR. Will continue to troubleshoot tomorrow.
- Will also create first NancyFx module unit tests for verifying REST paths are stable.

**Comment by mauroservienti** [comment]
Work is progressing nicely, thanks to @boblangley, in https://github.com/Particular/ServiceControl/pull/1421, all the PoA items are addressed by the linked PR (still in progress).

**Comment by boblangley** [comment]
## Status

The PR is as done as we can take it for now I think.

Testing Nancy module headers and internals will require some refactoring to make the modules testable, the dependency graph for building the unit tests is quite high. We should open another issue to tackle that separately.

**Comment by boblangley** [comment]
I think so @mauroservienti.

**Comment by mauroservienti** [comment]
## Status update

* Raised https://github.com/Particular/ServiceControl/issues/1431 to track the missing headers testing
* Waiting for @mikeminutillo to be back from NDC Sydney to review https://github.com/Particular/ServiceControl/pull/1421
* Once https://github.com/Particular/ServiceControl/pull/1421 is merged only missing thing is retrospective

**Comment by boblangley** [comment]
@mauroservienti and @dvdstelt it is time for a retrospective. Do we want to try it async?

**Comment by boblangley** [comment]
Retrospective completed. Closing issue.
