### ISSUE TITLE
[TODO] AuditImporter - fan out enrichers

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#1356]

**Comment by SzymonPobiega** [comment]
I am not sure this is a good idea since enrichers operate on the metadata dictionary which is not thread-safe. @Particular/servicecontrol-maintainers thoughts?

**Comment by WilliamBZA** [comment]
The written object is the `metadata` `IDictionary`, and all of the enrichers seem to write their own values instead of duplicating others (they use the `Add` method which would throw if there were already a key with the same value).

I think it would be ok to fan this out. It would be better to make the concurrent nature of this explicit though by using a concurrent dictionary.

**Comment by WilliamBZA** [comment]
Also, not necessarily required for a 3.0.0 release

**Comment by danielmarbach** [comment]
I double checked what @WilliamBZA said and can confirm they use all their unique keys. Sent in https://github.com/Particular/ServiceControl/pull/1361 to fix this TODO

**Comment by danielmarbach** [comment]
Merge the PR. Closing
