### ISSUE TITLE
[Minor / Limited] ServiceInsight result paging is broken when Service Control secured via a reverse proxy

### ISSUE THREAD

**Issue by janovesk** [Particular/ServiceControl#1448]
Paging message search results is done by including `next`, `prev`, `first` and `last` URLs in the response send from SC. The problem is these links are absolute (as opposed to e.g. message body link which is relative). When ServiceControl is secured behind a reverse proxy the public URL used to access it is different from the one SC listens on. The paging links contain the private URL which is useless in SI.

Example would be `/api/messages/` that returns a header like "Link=<http://localhost:33333/api/messages/?include_system_messages=False&per_page=50&sort=time_sent&direction=desc&page=1786>; rel=\"last\", <http://localhost:33333/api/messages/?include_system_messages=False&per_page=50&sort=time_sent&direction=desc&page=2>; rel=\"next\"" with "next" and "last" links. 

The code building these links assume that the incoming hostname can be used for the host part of the link. This is not true in scenarios where Service Control is accessed through a reverse proxy. (https://docs.particular.net/servicepulse/install-servicepulse-in-iis#advanced-configuration). In these scenarios, the request to the main hostname is processed by IIS before being forwarded to SC running at localhost. 

So the problem is:

1) A request is made to http://mysuperhost.com:33333/api/messages
2) IIS responsible for mysuperhost.com is a reverse proxy. It looks at the routing rules and finds that anything coming into http://mysuperhost.com:33333/api/ should be forwarded to http://localhost:33333/api/. It does.
3) SC gets the request as "http://localhost:33333/api/messages". 
4) SC assembles response with link header pointing to "http://localhost:33333/api/messages&whatever" because localhost is the incoming host for ServiceControl.
5) IIS returns the link header with "http://localhost:33333/api/messages&whatever" links, instead of links pointing to "http://mysuperhost.com:33333"

This, of course, is incorrect and anybody following these links, like ServiceInsight, will get a failure when they do.

By default, ServiceControl provides no access control. Using a reverse proxy is required to add basic access control to ServicePulse/ServiceControl. It is not uncommon or unreasonable scenario to support given the potentially sensitive nature of messages content available through the ServiceControl API.

We have a customer hit by this: https://c.eu1.visual.force.com/apex/Case?num=00039844

### Plan of action

 - [x] Decide on the solution
    - Modify ServiceInsight to replace the prefix on the absolute links with the connection URL
    - Modify ServiceControl to return relative links
    - Modify ServiceControl to return a new header with relative links and modify ServiceInsight to use the new header. Leave the old header as-is for backwards compatibility
 - [x] Implement the solution #1476 
 - [x] Bundled into 3.3.0, announcement amended
 - [x] Review the documentation on securing ServiceControl behind reverse-proxy

**Comment by SzymonPobiega** [comment]
I am pretty sure it used to work in the past as I've prepared the guidance on how to set up SC behind IIS. We might have broken it though 😢

**Comment by SzymonPobiega** [comment]
ServiceInsight already can handle relative URLs when dealing with message body: the message body URL is part of the message details document and is relative. SI, when detects a relative URL, uses the configured SC connection URL as the prefix.

As an alternative to setting up the rewrite rules for next, prev, last and first headers we could generate them as relative URLs in SC and SI should be able to handle it.

**Comment by janovesk** [comment]
The rewrite rules seems to be a PITA to setup with lots of manual steps, so I'm 👍 to avoid that.

**Comment by janovesk** [comment]
>ServiceInsight already can handle relative URLs when dealing with message body: the message body URL is part of the message details document and is relative. SI, when detects a relative URL, uses the configured SC connection URL as the prefix.

>As an alternative to setting up the rewrite rules for next, prev, last and first headers we could generate them as relative URLs in SC and SI should be able to handle it.

**Comment by danielmarbach** [comment]
Not sure we can justify a breaking change in how URIs are generated just like that because we think rewrite rules are a PITA. The idea is definitely valid and should be taken into account but we also started treating the exposes APIs in SC as publicized schema and therefore strictly speaking changing how the URIs are generated is a breaking change. Because it requires all consumers of the links to no longer treat them as absolute but suddenly relative. Given that we already have rewriting rules in place I cannot see how having one more makes the PITA index overflow to justify going for a breaking change as part of treating a bug.

**Comment by janovesk** [comment]
We would change the URIs to make it consistent. It's already happening for the body. We are inconsistent today. 

If we force more rewrite rules for everybody who uses a reverse proxy, we will double down on being inconsistent AND adding more manual steps for the end users to get this working. 

Compare this to the number of bespoke consumers of the SC API, I don't see a big problem.

**Comment by WilliamBZA** [comment]
ServicePulse has minimum SC API version but SI does not. SI is the only one that uses the next etc. links. We should verify how far back in the SI version tree relative links will work.

**Comment by SzymonPobiega** [comment]
This discussion here is my today's second example of a problem of *given there are multiple solutions to an issue, who decides which one gets implemented*. I think I'll raise a collab issue about that. Possible candidates to make the final call seem to be:
 * the person who raised the issue
 * the TF working on it
 * the squad that prioritizes and scopes it
 * the skills group who owns the repo

**Comment by janovesk** [comment]
There is also a more hacky solution available that would not entail a SC change or a rewrite rule for every user.

We could force SI to parse the next/prev/last links in that call as relative, even if they are returned as full. I it's full, strip the host, prepend the configured SC api host instead.

That would only need a SI update.

**Comment by SzymonPobiega** [comment]
@Particular/keeping-the-lights-on-squad talked about this extensively during last meeting. Some of the points we covered are:
 * We don't know if SI includes the credentials in the web requests so we don't know if it would be able to take advantage of reverse proxy-based authentication
 * The documentation we have about reverse proxy is under SP in the menu and talks specifically about SP so, in theory, we're not obliged to fix it for SI
 * We agreed this is not a security hole
 * We could not get into agreement if this is a low-prio bug (minor/limited) or a missing feature

We are going to talk about it again today

**Comment by WilliamBZA** [comment]
> We don't know if SI includes the credentials in the web requests

It doesn't, the authentication is handled by the path restriction by IIS. Not anything that we do.

> The documentation we have about reverse proxy is under SP in the menu and talks specifically about SP so, in theory, we're not obliged to fix it for SI

I don't see how what is documented reflects what we should fix or not in any way. Unless we can state that our documentation is perfect and complete, it can't be used as a metric for determining what is or isn't a bug.

We have a situation here that isn't working as it should. We have a blocked customer. Kicking this around to another bucket doesn't change the fact that something is broken and needs to be fixed.

**Comment by SzymonPobiega** [comment]
@WilliamBZA to unblock a custom all we need is help them craft these nasty header rewrite rules.

> [documentation] it can't be used as a metric for determining what is or isn't a bug

Then we are really unable to tell if this is a bug or not. Some people will say it is a bug because we should expect this to work and some will say they have different opinions. No hard facts, only opposing opinions.

**Comment by janovesk** [comment]
How exactly will one make the argument that this is not a bug?

**Comment by janovesk** [comment]
> We don't know if SI includes the credentials in the web requests so we don't know if it would be able to take advantage of reverse proxy-based authentication

This already works. Just try ServiceInsight through a reverse proxy. It will show you the first page of messages just fine, it's just the links for page 2++ that are wrong on that first request.

**Comment by janovesk** [comment]
> The documentation we have about reverse proxy is under SP in the menu and talks specifically about SP so, in theory, we're not obliged to fix it for SI

Wrong. https://docs.particular.net/servicecontrol/securing-servicecontrol is under ServiceControl/Security in the menu. 

It explicitly mentions reverse proxying as a way to secure SERVICE CONTROL and links to the actual intstructions which can arguable said is in the incorrect place under SP.

**Comment by SzymonPobiega** [comment]
> Wrong. https://docs.particular.net/servicecontrol/securing-servicecontrol is under ServiceControl/Security in the menu.

You're right. I didn't take this one into account. Then it definitely looks like a bug.

**Comment by SzymonPobiega** [comment]
@Particular/keeping-the-lights-on-squad I propose to categorize this as `Minor / Limited` and scope the issue as:

Enable secure communication and Windows authentication between SI and SC via IIS reverse proxy

Based on this statement from [the doco](https://docs.particular.net/servicecontrol/securing-servicecontrol#limiting-access-and-data-visibility-limiting-access-to-servicecontrol-using-windows-authentication)

> It is possible to setup IIS to act as a reverse proxy and secure ServiceControl using Windows Authentication

**Comment by SzymonPobiega** [comment]
@janovesk did verify that RestSharp used in SI handles Windows Authentication out-of-the box so SI is ready.

@Particular/keeping-the-lights-on-squad I've updated the issue description adding plan of action

**Comment by danielmarbach** [comment]
Happy to help out if you need an Axe

**Comment by SzymonPobiega** [comment]
@janovesk @WilliamBZA would you be able to join @danielmarbach and provide your bows and swords?

**Comment by janovesk** [comment]
Okay, I'll help out on this. Can @danielmarbach and I start on this @Particular/keeping-the-lights-on-squad ?

**Comment by janovesk** [comment]
We are ready to go next week

**Comment by timbussmann** [comment]
I have capacity as well if needed but no knowledge about the involved code tbh.

**Comment by SzymonPobiega** [comment]
OK. Assigning three of you here. @danielmarbach knows the codebase as don't worry @timbussmann . You can start next week. Do you want me to organize a kick-off meeting or you'll handle it yourselves?

**Comment by danielmarbach** [comment]
## Status update

We kicked off the work today and will update this issue as we move along. Stay tuned

**Comment by danielmarbach** [comment]
## Host header
Use X-Forwarded-Host and Host header to properly generated absolute URIs depending on whether SC is running behind a reverse proxy or not.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host

While this option is probably the most sophisticated and pure HTTP style solution it would have to be implemented for all URIs that are generated. It sounds more like this is a feature enhancement that can be planned for future releases of ServiceControl.
## Fix ServiceInsight only
ServiceInsight could be fixed to treat all absolute URIs as relative ones. With that customers who are currently stuck would not need to upgrade ServiceControl since this might involve Ops teams. Upgrading ServiceInsight is less intrussive. 

While this seems an easy and quick win we argued that how ServiceControl behaves currently if you follow its links is not correct. If you follow the links of ServiceControl as an API consumer you cannot use it behind a reverse proxy which is our recommended way of securing ServiceControl.
## Fix ServiceControl only
ServiceControl creates absolute and relative URIs already (for example for retrieving the body of a message). ServiceControl could be fixed to only return relative URIs. Then all URIs are aligned and no longer absolute. ServiceInsight can already handle absolute and relative URIs automatically and would not need to be changed.

ServiceControl APIs are not considered public and we always mention that caveat when we talk to customers about using those APIs. While changing from absolute to relative URIs might break a client those clients already today have to deal with relative URIs anyway. 
## Fix ServiceInsight and ServiceControl
Incorporate the changes from above for both products.

We think that is overkill and if necessary and there is demand from customers to have SI fixed as to work with a previous version of SC we could always do that if necessary at a later point in time.

## Recommended to move forward
Fix ServiceControl only and break the internal HTTP API. ServiceInsight can deal with those changes seamlessly. In the future consider making reverse proxying a better first-class citizen of SC by further investigating the use of Host and X-Forwarded-Host header.

**Comment by janovesk** [comment]
Reviewed and checked the box for the documentation. No need to fix anything there.
