### ISSUE TITLE
ESent error on importing of failed messages

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#1505]
We currently have 2 custom checks failing for our service control instance stating that we had audit and error messages that were unable to be imported.  We followed the documentation for importing failed audit messages.  The cli said it processed the 15 failed audit messages we had but then bombed out with an esent error shown below

```
2018-11-28 18:20:11.3995|12|Info|ServiceControl.Operations.ImportFailedAudits|Done re-importing failed audits. Successfu
lly re-imported 0 messaged. Failed re-importing 0 messages.
Disposing esent resources from finalizer! You should call TransactionalStorage.Dispose() instead!
Failed to dispose esent instance from finalizer because: Microsoft.Isam.Esent.Interop.EsentTooManyActiveUsersException:
Too many active database users
   at Microsoft.Isam.Esent.Interop.Api.JetTerm2(JET_INSTANCE instance, TermGrbit grbit)
   at Raven.Storage.Esent.TransactionalStorage.Finalize()
PS C:\Windows\system32>

```

We went to look at servicepulse and noticed the custom check for audit messages that need to be imported went away but the custom check for failed error messages that need to be imported is still there.  We tried running running service control using the —import-failed-audits which says nothing needs to happen and bombs out on esent again.

My questions are:

1. Does passing the —import-failed-audits also import failed error messages as well and is just poorly named?

2. How do we resolve this esent error from happening when needing to manually import failed messages?

3. How do I get my failed error messages imported?

4. When I put servicecontrol into maintenance mode and go to the port ravendb is listening on it shows no databases which seems completely wrong.  Where is the database servicecontrol is using?

I believe our version of servicecontrol is 2.1.2.  I can confirm this in the morning.

Any help is greatly appreciated

### Root cause

The `ImportFailedAuditsCommand` does not stop/dispose the `Bootstrapper` object.

**Comment by SzymonPobiega** [comment]
Hi @TraGicCode 

1. No, it does not import the failed messages
2. The `esent` error does not case the failed error messages to be not imported. It probably does not affect the failed audit import either. That's likely minor a resource management bug on our side. We'll fix it.
3. Currently the only option is to start the SC in the maintenance mode, go to the RavenDB studio and copy the messages from `FailedErrorImports` collection to a notepad of some sort and then move them back manually to the queue using native tools for your queues
4. The SC uses the system database of RavenDB, that's why it does not show the other databases.

**Comment by TraGicCode** [comment]
Hey @SzymonPobiega ,

1. Why do do error messages not get imported? We would love to see these and replay them if they are important like issues creating a customers order?

2. Are you able to reproduce this esent issue on your end?

3. The documentation states service is stores it’s information in a database called storage.  I will confirm the system database is indeed the correct name and report back here a bug

**Comment by SzymonPobiega** [comment]
Hey @TraGicCode 

Sorry I dropped a ball on this. Here are the answers
 1. SC does not have this feature. We're working on properly designing it so that it does not try to re-import malformed messages forever
 2. Yes, that's a double dispose problem that should be fixed in the next version
 3. That doco issue is now solved, right?

**Comment by SzymonPobiega** [comment]
@TraGicCode yes, you are right. We missed this one :\

**Comment by TraGicCode** [comment]
Hey @SzymonPobiega ,

When can we expect the next release to go out?

**Comment by SzymonPobiega** [comment]
@TraGicCode not yet sure :-(
