### ISSUE TITLE
ServiceControl won't start

### ISSUE THREAD

**Issue by markgould** [Particular/ServiceControl#1670]
Upgraded two instances of SC to 3.8.1 and neither will start (both on same server). Appears to start and then after 30 secs or so, goes back to stopped.

Seeing some raven error about "Failed to execute transaction" 

I've attached the log files. Let me know if I can do anything to further diagnose.

[Particular.ServiceControl-configuration.txt](https://github.com/Particular/ServiceControl/files/3259043/Particular.ServiceControl-configuration.txt)
[ravenlog.2019-06-05.txt](https://github.com/Particular/ServiceControl/files/3259044/ravenlog.2019-06-05.txt)
[logfile.2019-06-05.txt](https://github.com/Particular/ServiceControl/files/3259045/logfile.2019-06-05.txt)

**Comment by mikeminutillo** [comment]
@markgould I get slightly different symptoms but I'm pretty sure I am getting the same issue. I believe it is being caused by ServiceControl and the transport using different versions of Json.NET. As a temporary fix, you can put the right version into the folder and try to start the instances like this:

- Find the installation of ServiceControl Management. By default this is `C:\Program Files (x86)\Particular Software\ServiceControl Management`
- Open the zip file named `Particular.ServiceControl-3.8.0`
- In the ServiceControl subdirectory, take a copy of `Newtonsoft.Json.dll`
- Copy that file into the ServiceControl instance installation folder (linked in the Management Utility)
- Restart the instance

That should get you going again. I'll start working on an official fix and get it into 3.8.2.

Thanks for reporting this.

**Comment by markgould** [comment]
@mikeminutillo thanks for the quick response. That did indeed resolve it! The instance had version 10.x and the zip file had 12.x.

**Comment by mikeminutillo** [comment]
@markgould [3.8.2](https://github.com/Particular/ServiceControl/releases/tag/3.8.2) has now been released with this fix in place. Please upgrade your endpoints when you have an opportunity.
