### ISSUE TITLE
Unmonitored Endpoints keeps coming back

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#1715]
We have decommissioned some NServiceBus Endpoints and are wanting to tell servicecontrol to stop monitoring them so the heartbeat alerts go away.  From my understanding, since we cannot delete endpoints in servicecontrol, we must inform servicecontrol to ignore them from an heartbeat monitoring perspective.  When we do this servicecontrol no longer shows the endpoint as being monitored and no longer shows heart beat alerts for this endpoint in servicepulse.  If we come back sometime later in the day it magically shows up again as an endpoint being monitoring and missing heartbeats.  No matter how many times we try and unmonitor it it always comes back.

We have ensured the endpoint is uninstalled from all production machines and no longer running.

This definitely seems like a bug in servicecontrol :(

**Comment by DavidBoike** [comment]
Hi @TraGicCode, can you answer:

* ServiceControl & ServicePulse versions?
* Is this an elastic scale scenario or all stable endpoint instances running on well-defined machine names?
* Are you setting a [host identifier](https://docs.particular.net/nservicebus/hosting/override-hostid)?

**Comment by mikeminutillo** [comment]
May I add to that list?

- Are you using a multi-instance ServiceControl deployment?
- Is it possible that there are still messages sent by that endpoint in queues being processed by other endpoints?

The reason I ask is that when we ingest messages from the audit queue we add the sending endpoint and the receiving endpoint to the list of endpoints. It should not enable monitoring automatically when it does this though. I just want to try and figure out where SC is finding these endpoints.

If you can do this repeatedly, please look at the event log in ServicePulse shortly after the endpoint reappears. Whenever we enable or disable monitoring there should be an EventLog raised. If you don't use ServicePulse you can hit the `/api/eventlogitems?page=1&per_page=50` http endpoint of ServiceControl to get the results back as json.

If you can find the details of the EventLog entry, it will help us to diagnose exactly what is going on.

**Comment by mikeminutillo** [comment]
@TraGicCode did you end up getting this sorted? Is there any more info we can provide?

**Comment by TraGicCode** [comment]
Hey @mikeminutillo ,

No i have not.  I'm actually in the middle of closing on selling and buying a house but i will get more information when i can.

**Comment by TraGicCode** [comment]
Hey @mikeminutillo ,

Hopefully i will have more information on this today.  So one thing i noticed was that a developer changed the windows service name of an nservicebus host that caused 2 to be installed.  Therefore when it got decommissioned 1 got uninstalled but the other was hanging out still. 

I have removed the host fully from all servers and will wait and see if the issue goes away now :)

Thanks!

**Comment by TraGicCode** [comment]
**ServiceControl Version:**
3.8.2

**ServicePulse Version:**
1.20.1

**Elastic Scale Scenario:**
No

**Are you setting host identifier:**
Yes.  We has to do this because we use octopus deploy which deploys to the same machine but to different folders on the filesystem each time

```
var configuration = new EndpointConfiguration(profile.EndpointName);
                configuration.UniquelyIdentifyRunningInstance().UsingNames(profile.EndpointName, Environment.MachineName);
```

**Are you using a multi-instance ServiceControl deployment:**
No

**Is it possible that there are still messages sent by that endpoint in queues being processed by other endpoints:**
No

So it looks like the endpoint is showing up again as being monitored and also missing heartbeats.

![image](https://user-images.githubusercontent.com/6224270/61999952-f6ddfa80-b091-11e9-98a5-e99c04cfbb2d.png)


![image](https://user-images.githubusercontent.com/6224270/61999956-01988f80-b092-11e9-85ed-15650dad0969.png)

When i view the json result from service control's `api/endpoints` path this host is returned with the following data in the endpoints array which the date isn't correct:

```
[
..
..
,{
    "id": "40f54df6-18a9-a9f0-24b1-3acc8774f8e8",
    "name": "UserAccount.Host",
    "host_display_name": "2-P1-APP01",
    "monitored": true,
    "monitor_heartbeat": true,
    "heartbeat_information": {
      "last_report_at": "0001-01-01T00:00:00",
      "reported_status": "dead"
    },
    "is_sending_heartbeats": false
  }]
```

When i go to the following servicecontrol path `/api/eventlogitems?page=1&per_page=50` i was unable to even find anything regarding the `UserAccount.Host` endpoint anywhere

**Comment by mikeminutillo** [comment]
That is extremely odd. There's 3 ways that Monitoring can get switched on for an Endpoint instance:

- At startup, if the persisted endpoint data says that the endpoint should be monitored (you can see this in the KnownEndpoints document collection if you start ServiceControl in maintenance mode). This would require a ServiceControl restart for the endpoint to start monitoring again. Are you restarting your ServiceControl instance in between disabling monitoring and seeing it come back on?
- Monitoring is explicitly enabled by sending an HTTP Patch request to `/api/endpoints/{id}` with `MonitorHeartbeat` set to true in the Form data. As far as I know, only ServicePulse would be doing this. This should result in an EventLog entry with an `EventType` of `MonitoringEnabledForEndpoint`.
- We receive a heartbeat for the endpoint for the first time since we started. At startup, all endpoints are marked as status `Unknown`. If we see a heartbeat for an endpoint in an `Unknown` status then we start monitoring it and set it's status to `Alive`. I can see in the data that you provided that we have never seen a heartbeat for this endpoint. The `last_report_at` is `DateTime.MinValue`. This will result in an EventLog entry with an `EventType` of `HeartbeatingEndpointDetected`.

**Comment by TraGicCode** [comment]
> At startup, if the persisted endpoint data says that the endpoint should be monitored (you can see this in the KnownEndpoints document collection if you start ServiceControl in maintenance mode). This would require a ServiceControl restart for the endpoint to start monitoring again. Are you restarting your ServiceControl instance in between disabling monitoring and seeing it come back on?

Yes we frequently restart service control ( for upgrades or other reasons like config file changes ).  This seems like a bug in servicecontrol if restarting causes endpoints to be monitored again.

**Comment by mikeminutillo** [comment]
It is definitely not supposed to be working that way. When we receive the PATCH request from ServicePulse we try to update the persisted storage before changing the in-memory heartbeat monitor. Unfortunately we report success if there is no record to update (this is likely masking the bug).

My working theory from looking through the code is that the id on the KnownEndpoint document is not what we expect. I'm not sure how could happen but it fits the symptoms. 

When you disable monitoring through ServicePulse we'd try and update the persistent store but we wouldn't find anything because of the id mismatch. We still go ahead and update the in-memory monitor and stop monitoring. Everything looks fine until ServiceControl is restarted. As soon as that happens, our heartbeat warmup will load all of the documents and create the in-memory monitors with the state they have in the database (which is still Monitored).

To help me verify that this is what is going on, can I ask you to please disable heartbeat monitoring for the endpoint, switch ServiceControl over into maintenance mode, find the KnownEndpoint document for the endpoint instance, and upload a copy? I am looking for two things. I want to see if the Monitored flag is changing when you disable the endpoint, and I want to use the data in the document to generate an Id and see if it matches the one the document has.

**Comment by mikeminutillo** [comment]
Hi @TraGicCode, were you able to grab the data I requested in the previous comment?

**Comment by TraGicCode** [comment]
Hey @mikeminutillo ,

Sorry about getting back so late.  We just ended up removing the endpoint from servicecontrol's ravendb to resolve the issue fully.
