### ISSUE TITLE
Endpoints identified with UsingCustomDisplayName show different names depending on the operation

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#2066]
When a customer uses this API:

```csharp
endpointConfiguration.UniquelyIdentifyRunningInstance()
  .UsingCustomIdentifier(new Guid("1C62248E-2681-45A4-B44D-5CF93584BAD6"))
  .UsingCustomDisplayName("original-instance");
```

They get duplicated endpoints in ServiceInsight:

![image](https://user-images.githubusercontent.com/124014/86210442-374dce80-bba7-11ea-8f33-490a9823bd29.png)

This is because of the way we [extract `SendingEndpoint` and `ReceivingEndpoint` from headers in ServiceControl](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl.Audit/Monitoring/EndpointDetailsParser.cs).

For sending endpoints, we extract the header `NServiceBus.OriginatingMachine` and use it for the `Host` property of the endpoint. 

For receiving endpoints, we extract the header `NServiceBus.HostDisplayName` and fall back to `NServiceBus.ProcessingMachine` if that header is missing. Whichever we find is placed in the `Host` property of the endpoint.

The Host Display Name is not sent for a Sending Endpoint so if there's a discrepancy between these things, the endpoint shows up with two different Host properties. 

If you don't call `UsingCustomDisplayName` then it defaults to Machine Name so you won't see the discrepency.

**Comment by SzymonPobiega** [comment]
@mikeminutillo I looked at the code and it seems that `EndpointDetected` could be modified in such a way that it would return _canonical_ `EndpointDetails`:
 - if cache contains `EndpointDetails` with same HostId but not overridden host name and we try to add endpoint details with overridden host name then we replace item in the cache and return that instance
 - otherwise we do what we did before

This way we can "correct" the display for the messages after we receive at least once instance processed by the endpoint with overridden display name. This is not a bullet-proof solution as the messages before that one would still refer to the wrong instance. 

The correct solution probably is possible only on SI side. What do you thing? cc @tmasternak @seanfarmar

**Comment by tmasternak** [comment]
@SzymonPobiega can we break this down into two separate problems?

 * Single endpoint is displayed twice - no matter what is the name shown.
 * CustomDisplayName is not applied correctly for outgoing messages.

I think we could solve the first one by using HostId in SI. The second problem could partially solved by your proposal.

Should we fix the way that the message headers are set for the outgoing messages?

**Comment by tmasternak** [comment]
This has been [fixed](https://github.com/Particular/ServiceInsight/pull/897) in ServiceInsight [2.2.0](https://github.com/Particular/ServiceInsight/releases/tag/2.2.0) release.
