### ISSUE TITLE
Dismissal of custom check keeps coming back and sometimes shows duplicates in servicepulse ui

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#2086]
Hello,

How come when i go to dismiss a custom check, that has already been resolved ( in our case the "Failed to import too many times" message related to the error ingestion process custom check ) it comes back in servicepulse immediately and sometimes even shows duplicates to us.

![image](https://user-images.githubusercontent.com/6224270/88425705-71c91680-cdb5-11ea-80f2-3e5e0125aa09.png)

Maybe this is related to #2058 ?

**Comment by mikeminutillo** [comment]
@TraGicCode which version of ServiceControl is this? The way these custom checks are managed changed in 4.5.0.

**Comment by TraGicCode** [comment]
> @TraGicCode which version of ServiceControl is this? The way these custom checks are managed changed in 4.5.0.

We are currently on 4.10.2.

**Comment by mikeminutillo** [comment]
Very odd. That version is using the new way of doing things.

Each reported Custom Check should have an Id which is a hash of Endpoint Name, Host Id, and Custom Check name. All of those things should be immutable after the ServiceControl instance starts so I'm not clear on how we're showing duplicate entries.

If/when this next happens, can you please call the ServiceControl API directly to see exactly what it is returning? It should be something like `http://localhost:33333/api/customchecks`.

Under the covers we have two different timers involved here and by default they are both running every 5 seconds.

- The first timer is a watchdog process. It checks to see if the error ingestion task is running. If it's not, it starts it. If it fails to start, for any reason, it records that failure in memory. That in-memory failure persists until the watchdog is able to successfully start the error ingestion task.
- The second timer is a reporting process for custom checks. It looks to see if any in-memory failure has been recorded. If it has, then it reports failure of the custom check, otherwise it reports success. 

If the error ingestion task is not successfully starting, then the in-memory failure will persist, and the custom check will keep reporting failure. It will re-appear every 5 seconds.

If that is what is happening then you should see something like this in the logs:

> Error while trying to start {processName}. Starting will be retried in {timeToWaitBetweenStartupAttempts}.

But the error being reported is `Failed to import too many times`.  This happens when the error ingestion process fails to import more than 50 messages within a 20 second window. The system responds by shutting down the error ingestion process, assuming that something is wrong. It also writes to that in-memory failure that the custom check will report on. 

Within 5 seconds, the watchdog timer will go off and try to restart the ingestion task. It may be that it is successful but another 50 messages fail to import within the next 20 seconds and the system shuts down errror ingestion again.

Note that those 50 failures within 20 seconds are all coming from messages that we have attempted to process 3 times already, so there is definitely a persistent problem at play here.

Can you check your windows event log for messages that look like:

> A message import has failed. A log file has been written to {path}

**Comment by TraGicCode** [comment]
Here are the api calls on that page:

**/api/customchecks?status=fail**

`[{"id":"307b43ca-b205-d837-900d-46bad9a3cfcf","custom_check_id":"Error Message Ingestion","category":"ServiceControl Health","status":"fail","reported_at":"2020-07-29T13:39:42.9148115Z","failure_reason":"One or more error messages have failed to import properly into ServiceControl and have been stored in the ServiceControl database.\r\nThe import of these messages could have failed for a number of reasons and ServiceControl is not able to automatically reimport them. For guidance on how to resolve this see https://docs.particular.net/servicecontrol/import-failed-messages","originating_endpoint":{"name":"Particular.ServiceControl.prod","host_id":"38e4f9c9-53b5-9aae-9e67-a1ed6c8de31c","host":"CVPAPP08"}},{"id":"e529ce10-65ae-f9ff-5150-104ea0ec5de4","custom_check_id":"Error Message Ingestion Process","category":"ServiceControl Health","status":"fail","reported_at":"2020-07-29T13:58:16.7128925Z","failure_reason":"Failed to import too many times","originating_endpoint":{"name":"Particular.ServiceControl.prod","host_id":"38e4f9c9-53b5-9aae-9e67-a1ed6c8de31c","host":"CXXX08"}}]
`
**/api/customchecks?status=fail&page=1**

`[{"id":"e529ce10-65ae-f9ff-5150-104ea0ec5de4","custom_check_id":"Error Message Ingestion Process","category":"ServiceControl Health","status":"fail","reported_at":"2020-07-29T14:03:42.2195973Z","failure_reason":"Failed to import too many times","originating_endpoint":{"name":"Particular.ServiceControl.real-prod","host_id":"38e4f9c9-53b5-9aae-9e67-a1ed6c8de31c","host":"CXXX08"}}]
`

**/api/customchecks?status=fail&page=1**

`[{"id":"e529ce10-65ae-f9ff-5150-104ea0ec5de4","custom_check_id":"Error Message Ingestion Process","category":"ServiceControl Health","status":"fail","reported_at":"2020-07-29T14:03:42.2195973Z","failure_reason":"Failed to import too many times","originating_endpoint":{"name":"Particular.ServiceControl.prod","host_id":"38e4f9c9-53b5-9aae-9e67-a1ed6c8de31c","host":"CXXX08"}}]`


Here is the screenshot of the XHR requests when that page is loaded.

![image](https://user-images.githubusercontent.com/6224270/88810403-e962c100-d17a-11ea-89ec-85cfe51ebe2c.png)


@mikeminutillo out of the 3 calls above the last 2 are duplicates.

**Comment by mikeminutillo** [comment]
@TraGicCode Can you check the headers on those two requests? I am looking for a `Total-Count` header that should control the infinite scroll. I don't think that's the problem because then I would expect a `page=2`.

The first request is used to get the total count of custom checks and is OK.

I think this might a ServicePulse problem. If for any reason, the `CustomChecksUpdated` event is fired multiple times in rapid succession, it's possible that there's a race condition here

https://github.com/Particular/ServicePulse/blob/master/src/ServicePulse.Host/app/js/views/custom_checks/customChecks.controller.js#L29-L52

The event fires twice, clears the model twice, calls `load` twice. Both loads fire off simultaneously, and then return. Each one adds the same custom check to the model and then figures out there's no more data and disables the infinite scroll.

**Comment by TraGicCode** [comment]
Hey @mikeminutillo ,

Total-Count header on both of those requests was 2

**Comment by mikeminutillo** [comment]
@TraGicCode this is definitely a bug and we'll be working to get it included in one of our upcoming maintenance releases. Thanks for raising it.

**Comment by TraGicCode** [comment]
Hey @mikeminutillo ,

Are u able to link this to an issue in the servicepulse repository or migrate this issue over there so I can keep track of it?

Thanks!

**Comment by TraGicCode** [comment]
@tmasternak Closing this now.  Will re-open if it happens when we test using the new version.
