### ISSUE TITLE
ServiceControl API reports incorrect license details

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#2582]
When a license is passed in to ServiceControl via the `ServiceControl/LicenseText` setting, it is used for the initial license check to start the application. It is not used for the period license check, or for the API controller that exposes the license status. 

The same problem is exhibitied by ServiceControl Monitoring with the `Monitoring/LicenseText` setting.

These settings are usually used when configuring ServiceControl within a docker container.

**Comment by DavidBoike** [comment]
This appears to have been fixed by accident with the release of Linux-based ServiceControl containers.

The key name is `PARTICULARSOFTWARE_LICENSE` as [documented here](https://docs.particular.net/nservicebus/licensing/#license-management-environment-variable), which has worked since Linux containers were introduced.

This was not a breaking change because Windows-based containers were never officially supported. `ServiceControl/LicenseText` and `Monitoring/LicenseText` were never documented outside of the contexts of a Windows container.

To verify, I also checked the `Version6Docs` archival tag in the repo for the configuration file pages for the [primary](https://github.com/Particular/docs.particular.net/blob/Version6Docs/servicecontrol/creating-config-file.md) and [monitoring](https://github.com/Particular/docs.particular.net/blob/Version6Docs/servicecontrol/monitoring-instances/installation/creating-config-file.md) instances and validated that there was never any mention of license on either of those pages that would have applied to Windows (SCMU/Powershell) based instances.
