### ISSUE TITLE
Deleted endpoint is still listed in /api/endpoints/known

### ISSUE THREAD

**Issue by CoeckelberghPJ** [Particular/ServiceControl#2590]
After doing some cleanup I noticed that one of the endpoints I've deleted is still listed in api/endpoints/known although it doesn't exist anymore in api/endpoints.
Whenever trying to delete it again through DELETE /api/endpoints/{id} I get a 404 response. 
Because of this we still see this non-existing endpoint in ServiceInsight.

To be clear I deleted around 5 endpoints but only 1 of them wasn't deleted from the known endpoints.

**Comment by WilliamBZA** [comment]
ServiceInsight uses different logic for it's set of known endpoints to ServicePulse. The DELETE within ServiceControl only removes endpoints from being displayed in ServicePulse, whereas ServiceInsight will still show endpoints if there are corresponding audit or error messages for that endpoint. The only way to remove the endpoints from ServiceInsight is for the audit retention period to expire so that the endpoint is removed, or for the failed message to be deleted or retried and the error retention period to expire so that the endpoint is again cleared up that way.

**Comment by CoeckelberghPJ** [comment]
Thank you for the info. 
After some further investigation, we couldn't find any error/audit messages, and based on the retention period the endpoint shouldn't have been listed anymore.
Although after updating to the latest version the endpoint was deleted from the known endpoints.
