### ISSUE TITLE
Deployment orchestration of ServiceControl containers

### ISSUE THREAD

**Issue by levimatheri** [Particular/ServiceControl#2874]
I'm working on a POC to set up ServiceControl in docker containers and run them in a Service Fabric cluster. I'm wondering how to orchestrate the deployment of the containers since they have dependency on each other. Particularly, I'm wondering how I can configure the audit instance so that the error instance is stopped and the `ServiceControl/RemoteInstances` added as an environment variable, according to the instructions below. I'm guessing there might be some scripting involved?
![image](https://user-images.githubusercontent.com/16405269/169620987-8320843c-188b-4282-9e2f-e8b72fb3df57.png)

**UPDATE**
It seems like there's a contradiction between the order in which the instances should be started. In [this published article](https://docs.particular.net/servicecontrol/containerization/#running-servicecontrol-using-docker-audit-instances), it says to set up audit instance after error instance is running. However in the [GitHub readme](https://github.com/Particular/ServiceControl#how-to-build-and-run-docker-images), it says to set up the audit instance first before the error instance, which I think the latter would simplify my setup. So, which is the right way?

**ARTICLE**:
![image](https://user-images.githubusercontent.com/16405269/169621581-7bf874a7-ffb4-4781-ad96-c2bf3b5bcf5c.png)

**GITHUB README**:
![image](https://user-images.githubusercontent.com/16405269/169621729-6873d749-74cc-4442-9fbe-2de328fd392f.png)

Any help is appreciated.

**Comment by dvdstelt** [comment]
Probably best to forget (most of) the documentation on the GitHub page, it's there for development purposes, not meant as documentation.

The [other document you mentioned](https://docs.particular.net/servicecontrol/containerization/#running-servicecontrol-using-docker-audit-instances) is indeed the documentation. But you can only find it through search and not in the menu. The reason is because of this:

```
ServiceControl cannot perform a graceful shutdown which can result in manual intervention to repair the underlying datastore. The base Windows operating system images do not support notifying the application that it is being shut down when running `docker stop`.
```

This literally means that if you bring down a container, you might lose data and/or corrupt the underlying RavenDb database. Since you're running this in a cluster where you (I expect) don't have control on when nodes will be added and removed, you'll likely run into this issue more often than you'd like. The reason is that Windows containers don't work as well as we expected. And we can't run ServiceControl on Linux yet, due to certain reasons, which we're working on.

Now on your question, I have no idea how to set this up in a ServiceFabric cluster. But as far as I know, the references to other instances of ServiceControl don't all have to be up at the same time. The most important one is the **primary** error instance. ServicePulse and ServiceInsight talk to the primary instance only.
You can find more information on setting up multiple instances here: https://docs.particular.net/servicecontrol/servicecontrol-instances/distributed-instances#overview-sharding-audit-messages-with-competing-consumers

**Comment by levimatheri** [comment]
Thank you for the clarification @dvdstelt
