### ISSUE TITLE
Support for Linux containers

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#3651]
We are currently working on enabling ServiceControl to run in Linux containers.

The work is broken down into distinct steps. As each step is completed, a new version of ServiceControl will be released and this issue will be updated.

Based on the remaining work we are 90% confident that we will be able to produce Linux container images for all types of ServiceControl instances by the end of June 2024. 

This estimate will be revised each time that the issue is updated.

Subscribe to notifications on this issue to stay up to date.

_This issue is locked to ensure that notifications are sent only for progress updates. Please use the [Particular Discussion Group](http://discuss.particular.net) for any questions, comments, or concerns._

## Overview

- ✅ Attempted in-place upgrade to RavenDB 5
- ✅ Split Audit capability into dedicated instance type
- ✅ Added option to run instances without ingestion
- ✅ Spike different persistence mechanisms
- ✅ Introduce persistence seam for ServiceControl Audit instances
- ✅ Add RavenDB 5 persistence seam implementation for ServiceControl Audit instances
- ✅ Introduce partial persistence seam for ServiceControl Error instances
- ✅ Make full-text indexing optional
- ✅ Switch from Windows-specific code to Microsoft Generic Host
- ✅ Created Windows docker container images for all ServiceControl instances
- ✅ Enabled selecting transport and persistence options at runtime
- ✅ [Upgrade persistence for Audit and Error instances to RavenDB 5](#user-content-ravendb5)
- ✅ [Produce versions of ServiceContol that run on .NET](#user-content-dotnet)
- ✅ [Produce Linux Docker images](#user-content-linux) _(in progress)_

Each step requires the previous one to be completed before it can be started.

## ✅ <a id="ravendb5" href="#user-content-ravendb5">Upgrade persistence for Audit and Error instances to RavenDB 5</a> _(complete)_

- ✅ ServiceControl Audit instances _(completed)_
- ✅ ServiceControl Monitoring instances _(N/A — do not persist data)_
- ✅ ServiceControl Error instances _(completed)_

ServiceControl stores data in an embedded RavenDB instance. Older versions of RavenDB require .NET Framework and use [ESENT](https://en.wikipedia.org/wiki/Extensible_Storage_Engine) (a Windows component) for storage, which means they can't run on linux. RavenDB 5 targets .NET and uses [Voron](https://ravendb.net/docs/article-page/csharp/server/storage/storage-engine) for storage), which means it _can_ run on Linux.

The change from ESENT to Voron makes it impossible to perform an in-place upgrade. We are introducing a persistence abstraction to allow us to choose an implementation at runtime.

```mermaid
graph TD
  ServiceControl --> abstraction(Abstraction)
  abstraction -..-> raven35(RavenDB 3.5 implementation)
  abstraction -..-> raven5(RavenDB 5 implementation)
```

ServiceControl Audit instances can already use RavenDB 5. All new instances target RavenDB 5 and we have [instructions for migrating existing instances from RavenDB 3.5 to RavenDB 5](https://docs.particular.net/servicecontrol/upgrades/zero-downtime).

## ✅ <a id="dotnet" href="#user-content-dotnet">Produce versions of ServiceContol that run on .NET</a>

_We are using the terms ".NET" and ".NET Framework" as described in [".NET vs. .NET Framework for server apps"](https://learn.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server)._

Parts of ServiceControl still require .NET Framework, which is not available on Linux. To run on Linux, all of ServiceControl must run on .NET. 

Going forward, we will migrate ServiceControl from .NET Framework to .NET. Among other things, this will require us to switch from from ASP.NET Web API to ASP.NET Core and switch to a version of SignalR which runs on .NET (which requires a corresponding change to ServicePulse).

## ✅ <a id="linux" href="#user-content-linux">Produce Linux Docker images</a>

There are still a few "features" of ServiceControl which absolutely require Windows:

- Running as a Windows service
- Configuration using the Windows Registry
- Sending critical errors to the Windows Event Log

We will modify these features in the .NET version of ServiceControl, providing appropriate alternatives for Linux environments, and publish Docker images for each type of ServiceControl instance.

**Comment by mauroservienti** [comment]
We would like to share an update on our progress on [producing versions of ServiceControl that run on .NET](https://github.com/Particular/ServiceControl/issues/3651#user-content-dotnet).

The ServiceControl master branch (not yet released) now runs on .NET 8. The codebase has been migrated to use ASP.NET Core 8, ASP.NET Core SignalR 8, and NServiceBus 9.

We discovered that the changes in SignalR are more complex than expected, so it is taking longer than anticipated to guarantee that ServicePulse and ServiceInsight remain compatible with the new version of ServiceControl. 

The remaining work to produce versions of ServiceContol that run on .NET is:

* Ensure ServicePulse is compatible with ServiceControl running on .NET (as well as older versions running on .NET Framework)
* Complete the testing phase and fix any issues blocking the release

After that, work will begin immediately to [produce Linux Docker images](https://github.com/Particular/ServiceControl/issues/3651#user-content-linux), which we expect to be much less complex than the previous steps.

We're 80% confident we can provide Linux container images for all types of ServiceControl instances by the end of June 2024. We'll provide another update when we've produced versions of ServiceControl that run on .NET.

**Comment by mauroservienti** [comment]
With the release of [ServiceControl 5.2](https://github.com/Particular/ServiceControl/releases/tag/5.2.0), all the blockers to supporting Linux containers (the dependency on .NET Framework and classic ASP.NET) have been removed.

Details for how to upgrade to the new version can be found in the [upgrade guide](https://docs.particular.net/servicecontrol/upgrades/5.1to5.2).

The work to produce Linux container images has already started. We are 90% confident that we will be able to provide Linux container images for all types of ServiceControl instances by the end of June 2024. We'll provide another update when we have more information about the progress of the container images work.

**Comment by DavidBoike** [comment]
While we aren't 100% done with all the documentation, we know you're all looking forward to having ServiceControl on Linux containers. So today, we're doing a soft release so you can test things out.

ServiceControl uses 4 different container images:

* [particular/servicecontrol](https://hub.docker.com/r/particular/servicecontrol) - the Error instance
* [particular/servicecontrol-audit](https://hub.docker.com/r/particular/servicecontrol-audit) - the Audit instance
* [particular/servicecontrol-monitoring](https://hub.docker.com/r/particular/servicecontrol-monitoring) - the Monitoring instance
* [particular/servicecontrol-ravendb](https://hub.docker.com/r/particular/servicecontrol-ravendb) - the database used by the Error and Audit instances
  * Note that it's highly recommended that the Error and Audit instances both have _independent_ database containers.

We will be working on shaping up the official documentation over the next couple weeks, but we think the documentation for each image on Docker Hub should give you enough to play with if you just can't wait. We'll continue to post updates on this thread as work on the documentation progresses.

We've also created a dedicated thread on our discussion site for [ServiceControl on Linux containers early access questions](https://discuss.particular.net/t/servicecontrol-on-linux-containers-early-access-questions/4000). We'll be monitoring that thread carefully for questions and feedback. We'd love to hear from you there. There's still the opportunity to incorporate feedback into additional releases during the month of July.

We know you've been waiting for this for a long time. Take it for a spin and let us know what you think.

**Comment by DavidBoike** [comment]
Today we've made major updates to the ServiceControl documentation in support of containers. The documentation previously leaned very heavily on ServiceControl Management, so in addition to documenting the container bits, we also had to do quite a lot of restructuring.

Here are some highlights in the new documentation:

* Container deployment docs for each instance type:
  * [Error instances](https://docs.particular.net/servicecontrol/servicecontrol-instances/deployment/containers)
  * [Audit instances](https://docs.particular.net/servicecontrol/servicecontrol-instances/deployment/containers)
  * [Monitoring instances](https://docs.particular.net/servicecontrol/monitoring-instances/deployment/containers)
  * [Database containers](https://docs.particular.net/servicecontrol/ravendb/deployment/containers)
* [Migration guide from Windows to containers](https://docs.particular.net/servicecontrol/migrations/windows-to-containers)
  * The migration process leans heavily on the same procedures previously used for migrating from RavenDB 3.5 to RavenDB 5. This process been generalized in [Replacing Error instances](https://docs.particular.net/servicecontrol/migrations/replacing-error-instances/) and [Replacing Audit instances](https://docs.particular.net/servicecontrol/migrations/replacing-audit-instances/)
* The configuration pages for [Error](https://docs.particular.net/servicecontrol/servicecontrol-instances/configuration), [Audit](https://docs.particular.net/servicecontrol/audit-instances/configuration), and [Monitoring](https://docs.particular.net/servicecontrol/monitoring-instances/configuration) instances have been updated so it's clearer how to set the value whether you're using an App config key, Environmnent variable, or ServiceControl Management field.
* The [ServiceControl Transports](https://docs.particular.net/servicecontrol/transports) page has been updated to document the transport types that were previously only available in the ServiceControl Management dropdown or via a PowerShell cmdlet.

And we're not done…

* Soon we'll be releasing a new version of ServiceControl that allows for setting the instance/queue name in containers. (This was always based on the Windows Service Name before, which makes no sense for containers.)
* We're adding reverse proxy capabilities to our ServicePulse container, so that communication with ServiceControl and Monitoring goes through the same host as ServicePulse, giving you a single point of ingress/egress to secure with SSL and authentication.
* We're still working on samples/documentation for compose/k8s.

Stay tuned…
