### ISSUE TITLE
Service fails to start if logging path is not available

### ISSUE THREAD

**Issue by nsneeringer** [Particular/ServiceControl#436]
If a logging path is specified in the SC config file, and if that path is not reachable, the SC service fails to start.

ServiceControl/LogPath = "\\SomeShare\ServiceControl\Logs"

The logging path was available when the service was installed and the service started and logged to it successfully.

The share for the logging path went down, and the service failed to start.

I expected SC to log to the default logging path or to the service's directory.

**Comment by gbiellem** [comment]
HI @nsneeringer 

This isn't something we plan to implement
We'd recommend using a local logging location rather than a UNC path. 

The scenario you mentioned was on startup but the UNC logging location could also become unavailable while the SC service is running.  I suspect this would also have a detrimental affect on the service (crash or loss of info sent to the log)

We'd recommend you log locally and have a scheduled task to copy/archive the logs centrally.
