### ISSUE TITLE
ServiceControl.Contract Subscription Removal

### ISSUE THREAD

**Issue by aritchie** [Particular/ServiceControl#469]
If I uninstall a service that registered with servicecontrol.contracts, it will not remove the subscription from servicecontrol.  Subsequently, if the queue for the subscribed app is removed, servicecontrol will crash on startup because the subscriber queue is gone.

Workaround: manually remove the subscription from the servicecontrol internal db.

Version Found: 1.5.2

**Comment by gbiellem** [comment]
There is a circuit breaker for the external event dispatcher so it makes sense that this would blow up if the queue is removed.  

@andreasohlund @SzymonPobiega  If we do the proposed health page we could change this circuit breaker and report on this rather than shutting down the service.  Thoughts?

**Comment by andreasohlund** [comment]
>If we do the proposed health page we could change this circuit breaker and report on this rather than shutting down the service. Thoughts?

I like it, :+1:

**Comment by johnsimons** [comment]
@mikeminutillo should we just handle this in SC ?

**Comment by johnsimons** [comment]
I don't think SC should stop because the external integration is gone.
I say:
- we log;
- we can publish an event so that displays in SP;

@andreasohlund @mikeminutillo @gbiellem 
thougths ?

**Comment by mikeminutillo** [comment]
@johnsimons Agreed. Failure to connect to a subscriber should not bring down SC.

**Comment by johnsimons** [comment]
So do we fix this as part of 1.7 @mikeminutillo ?

**Comment by mikeminutillo** [comment]
In discussion with @andreasohlund and @johnsimons we have come to the conclusion that this behavior is correct for the current implementation. Due to the way Event Subscribers are handled in Message Driven Pub Sub we cannot know if all of the subscribers have been sent a copy of the integration event. If the failing subscriber is first in the list then there may be other subscribers out there who never get integration messages because a Subscriber before them in the list is bad. Given that we don't know what those other subscribers do, stopping ServiceControl and informing the user that there is an issue is the correct behavior.

**Comment by aritchie** [comment]
So anytime I uninstall a service that is working with the servicecontrol.contracts, I have to manually go into the internal database to remove the endpoint registration?  Does that not seem wrong?

**Comment by johnsimons** [comment]
> I have to manually go into the internal database to remove the endpoint registration? Does that not seem wrong?

Yes it does sound wrong, @mikeminutillo @andreasohlund we need to rethink this, this is not a viable option.

**Comment by gbiellem** [comment]
@johnsimons  I agree with you here - reopening.

**Comment by johnsimons** [comment]
@gbiellem half of this issue is actually fixed now, so
>if the queue for the subscribed app is removed, servicecontrol will crash on startup because the subscriber queue is gone.

has been fixed as part of v1.8.1 (see https://github.com/Particular/ServiceControl/releases/tag/1.8.1)

**Comment by gbiellem** [comment]
> half of this issue is actually fixed now

@johnsimons So what's left to do? If you think it's resolved then i guess close it

**Comment by johnsimons** [comment]
@gbiellem 
> I have to manually go into the internal database to remove the endpoint registration? Does that not seem wrong?

This is still not fixed

**Comment by mikeminutillo** [comment]
@gbiellem @johnsimons I agree that the current approach is not ideal. We rely on NSB Pub/Sub and that does not include the concept of transient subscribers. In a normal NSB system, if a subscriber cannot be reached your system is in an invalid state and the crash is the correct behavior. We should not alter this behavior in core without serious consideration.

If we feel that a missing subscriber is not a failing condition then perhaps using NSB Pub/Sub is the wrong approach. I know we have discussed a webhooks approach in the past.

**Comment by johnsimons** [comment]
> We should not alter this behavior in core without serious consideration.

@mikeminutillo are you referring to NServiceBus Core ?

**Comment by johnsimons** [comment]
I am closing this as done as much as possible for now.
In the future we need to reconsider the usage of NSB Pub/Sub
