### ISSUE TITLE
Queue name auto assigned is already in use

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#514]
- Adding new instance, error queue is auto assigned "error2"  
![image](https://cloud.githubusercontent.com/assets/122651/9594428/246f4074-509e-11e5-83b6-7aae7a6f310e.png)
- But if I change it to something else and then back to "error2", I get queue already in use!  
![image](https://cloud.githubusercontent.com/assets/122651/9594438/46b5c964-509e-11e5-91b8-ffa23358e4a4.png)
![image](https://cloud.githubusercontent.com/assets/122651/9594440/522ceeee-509e-11e5-9335-ce35f9e6416c.png)

**Comment by gbiellem** [comment]
@johnsimons  I don't see a good way to address this as the names are only supposed to be unique per transport and we have no transport selected on entering the screen perhaps.  To me that means we either don't set a default at all or set them to the error, audit etc and rely on validation to pick this i[ on submit

**Comment by gbiellem** [comment]
@distantcam @petersgiles @sergioc  thoughts on this?

**Comment by sergioc** [comment]
That sounds like a bug to me... @johnsimons didn't indicate that error2 is actually being used in another instance like the error implies.

**Comment by gbiellem** [comment]
Just to clarify - yes there was instance using "error2" so the validation message was correct.
The problem is the  method for suggesting a queue name is based on the current number of instances.  It just doesn't look to confirm if the queue name is "taken" prior to suggesting it.
This is caught by validation on submit so it's not going to cause misconfiguration.

The simple fix would be to increment until we don't clash with an existing queue name on any transport.  (remember we don't know the transport the user is going to choose yet).
This still seems a little wrong as I pointed out above - it is valid to have the same queue names on different transports.

**Comment by sergioc** [comment]
> it is valid to have the same queue names on different transports.

Why continue considering as valid queues with same name on different transports? When would that be helpful to have?

**Comment by gbiellem** [comment]
@sergioc.it would be valid when migrating endpoints from one transport to
another. For the duration of the migration you could have two instances of
servicecontrol on different transports both using the same queue names .
@johnsimons pointed this out and we've adjusted validation accordingly

**Comment by gbiellem** [comment]
As discussed in the sync suggesting alternate names for error, audit etc is non-sense as SC isn't going to be the first thing setup.   We will always default the names to the SC defaults and then let validation take it's course.     

I've fixed the instance name to not suggest a name that is already taken.
Also if there is already an instance I've not set a default for the port. First instance still gets suggested 33333.
