### ISSUE TITLE
Add "Advanced Configuration" options in Management Utility

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#576]
@sergioc 

I want to add an option to the installer to set/view some of the more advanced SC config options.   
It doesn't make sense to add these in the add/alter instance screens so I'd like to add a new screen for this and obviously we'll need to figure out how to get there... Advanced Config button in the row of buttons perhaps?

**Comment by gbiellem** [comment]
@petersgiles  thoughts on this?

**Comment by sergioc** [comment]
@gbiellem need some more info here:

> Advanced Config button in the row of buttons perhaps

I assume you're referring to adding a button next start/stop, edit config buttons for each instance - right?

Do we need those advanced config options available when adding a new instance?

Can you list the advanced options that you'd like to make available separately?

**Comment by gbiellem** [comment]
> I assume you're referring to adding a button next start/stop, edit config buttons for each instance - right?

Not necessarily suggesting that i want that particular solution,  just highlighting we need to add an entry point 

> Do we need those advanced config options available when adding a new instance?

No.  These setting tend to be tuning or debug options that are added after the instance has been running for a while

> Can you list the advanced options that you'd like to make available separately?

Sure. Here is a grab bag of some of them 

#### Heartbeats

- HeartbeatGracePeriod 
The period that defines whether an endpoint is considered alive or not. )

#### SC Data retention settings

- ExpirationProcessTimerInSeconds
- ExpirationProcessBatchSize
- HoursToKeepMessagesBeforeExpiring

#### SC Storage options

- MaxBodySizeToStore 
Controls the maximum size of message bodies stored by ServiceControl

#### Raven UI Settings

- Expose RavenDB ( Enables the HTTP Management UI  on/off )  

#### Raven DB tuning 
-  Various Memory and perf tuning settings, i won't list them here

**Comment by sergioc** [comment]
> It doesn't make sense to add these in the add/alter instance screens

@gbiellem why?

**Comment by gbiellem** [comment]
@sergioc  

Manipulating most of those settings isn't necessary for the majority of users and I'd prefer to not complicate the current add instance  screens even further.

I'm not entirely against them being accessible from the edit screen as long as we don't just tack the fields on the end of the current form.  It needs to be done in a way that clearly indicates they are advanced troubleshooting and tuning params.  Ideally the only reason a user would go to these settings would be that they've hit a problem and we or a docs article has directed them to change these setting to address it.

**Comment by petersgiles** [comment]
Would something as simple as this suffice?

![editscreen](https://cloud.githubusercontent.com/assets/1644481/10871899/e6990d94-8148-11e5-8675-91376614bfa6.png)

**Comment by johnsimons** [comment]
Or just a "Show Advanced settings" button and then we inline those extra settings, same as Chrome does it:
![image](https://cloud.githubusercontent.com/assets/122651/10871919/1e62d9d8-8141-11e5-9526-859d277324e5.png)

**Comment by petersgiles** [comment]
That could work

![editscreen](https://cloud.githubusercontent.com/assets/1644481/10871982/7f394b48-814b-11e5-84ee-a6ccd8231c4e.png)

**Comment by gbiellem** [comment]
@petersgiles & @johnsimons   the location you've proposed for the advanced option clashes with the validation errors summary

![capture](https://cloud.githubusercontent.com/assets/2351700/10872382/c821b512-8154-11e5-97e4-df7df62b25e2.PNG)

**Comment by johnsimons** [comment]
Make it part of the scroll bit, so add it at the end of the form scroll, makes sense

**Comment by petersgiles** [comment]
How it this for an option

![editscreen](https://cloud.githubusercontent.com/assets/1644481/10872477/ddf0f96e-8156-11e5-861d-1732d8ebd09e.png)

**Comment by petersgiles** [comment]
Or this...which is probably easiest to implement on an engineering level

![editscreen](https://cloud.githubusercontent.com/assets/1644481/10872549/618c8472-8158-11e5-8241-ab6054f05639.png)

**Comment by sergioc** [comment]
[This option](https://github.com/Particular/ServiceControl/issues/576#issuecomment-152874748) from @petersgiles is what I had in mind as well:

![sc installer 12](https://cloud.githubusercontent.com/assets/493451/10884734/00659c2a-817a-11e5-9367-9ac0a25271a3.png)

We don't place it inline with the current form in order make a clear separation.

It would be placed where the link to *save to template* was previously placed. It sits logically at in the area of the screen where you perform end actions, yet it is immediately visible as soon as you access this screen in edit mode. 

@gbiellem it conflicts with the error message because the error indication design is incorrectly implemented. I included the reference design above.

Once you click "Advanced options" it should open a modal:

![sc installer 13](https://cloud.githubusercontent.com/assets/493451/10884886/bc31d68a-817a-11e5-90e4-d45ca390ecc6.png)


You can also use grouping of fields there.

**Comment by gbiellem** [comment]
Discussed this with @sergioc. We going to go with an inline collapsible panel(s) similar to @johnsimons  suggestion [here](https://github.com/Particular/ServiceControl/issues/576#issuecomment-152872761) 

@sergioc  will provide a mock of how he'd like it implemented

**Comment by johnsimons** [comment]
U mean I win :wink:

**Comment by gbiellem** [comment]
@johnsimons I guess so ;)

**Comment by mikeminutillo** [comment]
@gbiellem Are these settings currently part of the unattended install system? 

We have a [support case](https://nservicebus.desk.com/agent/case/14973) where a customer is wanting to automate installation of SC instances including at least one of these advanced settings.

**Comment by gbiellem** [comment]
@mikeminutillo  not as yet.   So far as we add features to the GUI we've been adding them to the other install methods. This would also follow that process.  I'll chime in on the support case as the workaround would be a small script like this:

```ps
#Requires -Version 3
#Requires -RunAsAdministrator 

Add-Type -AssemblyName System.Configuration
Import-Module 'C:\Program Files (x86)\Particular Software\ServiceControl Management\ServiceControlMgmt.psd1'

# Add the key/value pairs you used to put in the -D options here copies
$customSettings = @{
    'ServiceControl/HeartbeatGracePeriod'='00:00:40'   # 40 Seconds
}

foreach ($sc in Get-ServiceControlInstances)  {

     $configFile = Join-Path $sc.InstallPath -ChildPath 'servicecontrol.exe.config'
     $map = New-Object System.Configuration.ExeConfigurationFileMap
     $map.ExeConfigFilename = $configFile
     $configManager = [System.Configuration.ConfigurationManager]::OpenMappedExeConfiguration($map, [System.Configuration.ConfigurationUserLevel]::None)
     
     $appSettings = $configManager.AppSettings.Settings
     foreach ($key in $customSettings.Keys) {
        $appSettings.Remove($key)
        $appSettings.Add((New-Object System.Configuration.KeyValueConfigurationElement($key, $customSettings[$key])))
     
     }                  
     $configManager.Save()
     Restart-Service $sc.Name
}
```

**Comment by johnsimons** [comment]
@gbiellem 

From the list you have compiled in https://github.com/Particular/ServiceControl/issues/576#issuecomment-152371514, it seems we have since have already added extra retention options, we also doing the maintenance toggle, which means we don't need the "expose raven".

So the only ones left are:
- VirtualDirectory
- HeartbeatGracePeriod
- ExternalIntegrationsDispatchingBatchSize
- MaximumMessageThroughputPerSecond
- ExpirationProcessTimerInSeconds
- ExpirationProcessBatchSize
- MaxBodySizeToStore
- HttpDefaultConnectionLimit

Should we go ahead and do these ?

**Comment by gbiellem** [comment]
Not virtualdirectory - I've not seen this used anywhere and we left it out of SC management and no one has complained
I seem to remember there was some talk of dropping some of the other settings listed too
Let's get on a call with some of the other @Particular/servicecontrol-maintainers before we decide anything

**Comment by johnsimons** [comment]
from experience if we want to reach the highest possible throughput the following settings need to be adjusted:
- ExpirationProcessTimerInSeconds -> This one really depends on message processing per second, the more messages processed, the lower this setting needs to be so that we can keep up with the deletion of documents, otherwise we keep increasing the disk space, this can be calculated based on batch size and msg throughput per sec
- ExpirationProcessBatchSize -> This one really depends on message processing per second
- MaximumMessageThroughputPerSecond -> this one I tend to set to 0 so it is disabled

All other settings I haven't had the need to tweak.

**Comment by gbiellem** [comment]
What about MaxBodySizeToStore?

**Comment by gbiellem** [comment]
The HttpDefaultConnectionLimit one I don't get - i don't see the downside of setting this it an appropriately high value
