### ISSUE TITLE
What happens when the license expiries?

### ISSUE THREAD

**Issue by kye** [Particular/ServiceControl#585]
In terms of nServiceBus.Host.exe, ServiceControl and ServicePulse, what happens when the license expiries? Does the host still run? Are messages throttled? Do the ServiceControl/ServicePulse websites work as expected?

**Comment by gbiellem** [comment]
You will be receive a license expired warnings in ServicePulse.  Aside from that we also log warnings I believe.  There is no reduction of message throughput and we don't prevent the services from running.
The last thing we'd want is a production outage because you had forgotten to renew or apply your new license in a timely manner.

**Comment by gbiellem** [comment]
As far as NSB goes we used to limit functionality on older versions of NSB versions when the license expired but we no longer do that - http://docs.particular.net/nservicebus/licensing/licensing-limitations

**Comment by kye** [comment]
Thank you Greg. We're trying to organise a renewal at the moment but it's getting the close. :)
