### ISSUE TITLE
Enable to copy ServiceControl's URI in ServiceControl management utility

### ISSUE THREAD

**Issue by sfarmar** [Particular/ServiceControl#602]
Currently it's only a link, it would be a better user experience if a user could copy this.
(in a call with a customer installing SP the user needed to copy the URI for SP's installation)

**Comment by gbiellem** [comment]
The link presented isn't always ideal for pasting into SP.  When the host is a wildcard we display something lime  http://*:33333/api which would not be useful.   Clicking on the link goes to localhost since that is one of the valid options when wildcarding. What would make sense to copy in that scenario?

**Comment by sfarmar** [comment]
When you don't use localhost the option to copy makes it so much easier to use...

When using localhost it is les of an issue.

On production servers you usually have only IE installed with max (default) security setting which is useless, as it downloads the response as json file, make sense?

**Comment by gbiellem** [comment]
@sfarmar yep makes sense
