### ISSUE TITLE
Package ServiceControl and ServicePulse as nuget packages

### ISSUE THREAD

**Issue by kye** [Particular/ServiceControl#622]
It would be useful if ServiceControl and ServicePulse were available through nuget packages. Those components are updates frequenly on Github but are rarely updated internally because it means I need to download and manually install the software in 4 different environments, on 8 different machines.

How does Particular deploy software on their own testing environment?

**Comment by rfree02** [comment]
balls

**Comment by rusty-bbag** [comment]
Agree

**Comment by petersgiles** [comment]
@kye 

Why would nuget be an improvement over using our MSI installers? 
Are you using a deployment tool like Octopus to deliver these products to your environment?

We did use Chocolatey for packaging but over time we found that there were low download rates and the Chocolatey api would change between versions making it difficult for us to provide a consistently good experience for our customers. Our customers use the Platform Installer and the msi quite happily and it seemed better for us to focus on making sure those provided a quality installation experience.

> How does Particular deploy software on their own testing environment?

We do it manually. The reason is, that when we do integration tests, we are usually emulating a customer's environment to test a case or a particular problem they might be having.

**Comment by kye** [comment]
>Why would nuget be an improvement over using our MSI installers? 
It would make it easier for us since we'd be able to point Octopus at a public nuget feed and include the latest version in our deployments rather then manually checking the Github website installing the software each time.

>Are you using a deployment tool like Octopus to deliver these products to your environment?
Yep. Current in Dev and Test and we just got approval for PreProd and Prod.

I'll try scripting the MSI install so we stay up to date. :)

**Comment by petersgiles** [comment]
@kye you might be interested in these

ServicePulse http://platformupdate.particular.net/servicepulse.txt
ServiceControl http://platformupdate.particular.net/servicecontrol.txt
            
and you might find the powershell we used in Chocolatety usefull https://github.com/Particular/ServicePulse/tree/1.3.0/src/Setup/chocolatey

Depending on how clever you want to be it wouldn't be too hard to watch the release feeds (they have json headers) and then pull the msi's down and the automatically create nugets to put on your own corporate feed.

If you get completely stuck ping me via email

**Comment by kye** [comment]
Thank you @petersgiles. I'll give it a try.

**Comment by sveinfid** [comment]
@kye How did it work out? Did you use the feeds from @petersgiles to include the latest versions in your deployments?
