### ISSUE TITLE
ArchiveAllInGroup might result in archiving future errors in case of a backlog or staleness

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#649]
The command does not include a timestamp. When the user selects this action then this is based on stale data. When the command is processed in the future new items could have been added to the group.

**Comment by johnsimons** [comment]
This is by design, we archive or retry all messages that we find that match the group.

We have previously discussed this and could not come up with a reason not to do it.
What issue do you see with this approach, wouldn't a user want to retry or archive all messages that belong to a group regardless ?

**Comment by ramonsmits** [comment]
@johnsimons If you would currently see 12 message in a group, when clicking archive and the processing it could now be 12.000 messages while the operator think it archived 12 messages.

Based on what you say all future message should be automatically be archived too as they match the group.

**Comment by johnsimons** [comment]
> Based on what you say all future message should be automatically be archived too as they match the group.

Yes that is exactly what we do, as I said before, it is by design, we are aware of it.

**Comment by mikeminutillo** [comment]
Even if we were to timestamp the message when the user clicks the Archive button, we don't know if any messages have arrived between when we originally showed the groups in Pulse and now. If we are going to put a timestamp in it needs to be from query time.

**Comment by mauroservienti** [comment]
We already have the information we need, the `ETag`, is a sequential GUID always incremented (like the SQL rowversion or timestamp but database wide), if we include the highest `ETag` value in the returned group we could use that information as a cut off.

**Comment by mikeminutillo** [comment]
`Etag` would do it. There is an `IndexQuery.CutoffEtag`.

**Comment by mauroservienti** [comment]
Using that will also solve the following scenario:

* User retry a message in a group
* While the message retry is in progress the user archives the group
* The retried message fails once again right before the archive group is executed
* Since the failed message `ETag` changes cause we increment the attempts count the just failed message won't be archived

**Comment by mauroservienti** [comment]
As discussed the scenario we would like to address is the following:

1. User looks at Failed messages group from ServicePulse
* Identifies a group whose last failed message failed a week ago
* Decide to archive the group thinking that the issue is solved and due to the fact that messages cannot be retried
* The archive request is sent as a message to ServiceControl and queued for processing
* In the meantime new failed messages come in and are added to the same group
* As the archive request is processed new failed messages will be archived

The potential results are 2:

1. data loss: the new failed messages are never seen by the user and given that there is no way to query archived messages they are basically lost
* Confusion: if the user between (4) and (5) is looking at ServicePulse UI starts seeing new failed messages coming in but as soon as the archive request is processed (6) they disappear

**Comment by ramonsmits** [comment]
Doesn't have to be a week ago, other causes like having a huge backlog of messages.

**Comment by ramonsmits** [comment]
@mikeminutillo @johnsimons It seems a decision has been made to not fix / change the behavior. Can you please add the arguments for this decision?

**Comment by mikeminutillo** [comment]
@ramonsmits When John and I discussed this we came to the conclusion that it works as designed. When a customer takes an action on a group of failed messages, they are affecting a whole class of messages. They have not looked at each of the affected messages individually and made a decision on each one. 

Apologies for not giving reasons when we closed this.

**Comment by johnsimons** [comment]
@ramonsmits to add to @mikeminutillo answer, the misunderstanding as I see it is that ServicePulse shows a counter of messages, so the expectation is for that exact number to be the set to be dealt with.
If this is it, we may need to change ServicePulse to not give that impression and I would recommend raising an issue over there.

**Comment by ramonsmits** [comment]
@johnsimons @mikeminutillo What period would be allowed to justify this behavior? Failing messages 1 second, 10 seconds, 1 minute an hour or day in the future that would still match this group? Based on this decision an operator could start this group archive. That is first queued, if that will be processed after hours because other huge groups are also archived would that still justify this behavior?
