### ISSUE TITLE
Add SLR indicator header

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceControl#65]
As Opie, I would like to be notified when there are many or increasing number of SLRs performed, so I can investigate further if this is an indication of system instability (and I will be able to take corrective actions before it deteriorates further).

**Implementation proposal:**
SecondLevelRetriesPerformed : true|{false}

**Note:**
In order to conserve header space, avoid sending the header when SLR were not performed (i.e. the very existence of the header is an indication of it being true; the value of false is optional).

**Comment by andreasohlund** [comment]
I think the way to go here is that instead of a header we should create a plugin that hooks into the notifications,  http://docs.particular.net/nservicebus/errors/subscribing-to-push-based-error-notifications. This way we can let the users set threshold for flr/slr per second and have the plugin notify SC when that happens?

Arguable this could be implemented and distributed as a custom check? 

We could start by adding this as a sample to gauge interest?

**Comment by johnsimons** [comment]
@Particular/servicecontrol-maintainers 
I propose we close this one until we ready to tackle it?

**Comment by SimonCropp** [comment]
@johnsimons if u close it how would distinguish it from all the other issues that are closed "as fixed"?

**Comment by johnsimons** [comment]
@SimonCropp no milestone associated

**Comment by SimonCropp** [comment]
@johnsimons so u regularly go through the 268 closed issues with no milestone as part of your backlog pruning? https://github.com/Particular/ServiceControl/issues?q=is%3Aissue+no%3Amilestone+is%3Aclosed

**Comment by johnsimons** [comment]
Not sure what you are talking about @SimonCropp.
If we close this issue and later this topic resurfaces, I am pretty sure we can find it and reopen.

**Comment by andreasohlund** [comment]
I have a demo going that shows how to do this without a header and instead using a custom check to "alert" in SP when SLR rates go up. How about I get that recorded and we close this one as won't fix?

**Comment by andreasohlund** [comment]
Still think agree with @SimonCropp that we shouln't just close issues that we still might act on. Perhaps move it some where of add a bullet point to some more generic "crazy SC ideas" issue.

How about we discuss this in plat dev since this is relevant for all our repos?

**Comment by mauroservienti** [comment]
> Still think agree with @SimonCropp that we shouln't just close issues that we still might act on.

Agree.

**Comment by johnsimons** [comment]
> we shouln't just close issues that we still might act on

In my view, closing a feature request does not imply that we will not be acting on, it just means that right now the focus is elsewhere. It just help us concentrate on issues/features that are currently important. Having this massive backlog of open issues IMO makes it difficult to figure out where we going. The way I see it, is open feature requests that we do not intend to work on (right now), are just clutering the system, and also sending the wrong message to user out there, the fact is that we have no idea when we are going to tackle any of these or even if we ever going to do it at all.

> I have a demo going that shows how to do this without a header and instead using a custom check to "alert" in SP when SLR rates go up

@andreasohlund that would be great, looking forward to it.

**Comment by gbiellem** [comment]
@johnsimons 

As @andreasohlund  said let's have to discussion about do we or don't we close issues in platform dev.

**Comment by mauroservienti** [comment]
yeah, let's discuss it. I don't think we should close issues, a closed issue is a lost one, IMO. If a huge backlog is putting pressure on us it's a tolling problem (and to be honest GitHUb issues suck) since we have no way (other than the waffle boards, that are not that much better) to prioritize and look only at the top N issues. Also given that we have no milestones set in stone priorities may change overtime and is very easy to lose track of closed issues that were closed because of lack of capacity or out of scope at that time.

**Comment by johnsimons** [comment]
@mauroservienti it is quite simple to keep track of feature requests that were closed.
This query gives u all issues that are closed and have no associated milestone and are not bugs
https://github.com/Particular/ServiceControl/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+no%3Amilestone+-label%3A%22Type%3A+Bug%22+

**Comment by johnsimons** [comment]
This is currently not prioritised to be done any time soon, I will close this one for now and if we ever go down this path we can reopen it
