### ISSUE TITLE
License detection diagnostics and license info

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#671]
SC shows from which location it uses a licensen but not which locations it tried. I had an issue where I expected a location to be used but that was not happening.

The license that it found was expired but the log didn't mention details. I had to go into the registry to check license details.

**Comment by gbiellem** [comment]
see https://github.com/Particular/ServiceControl/issues/629#issuecomment-178352526

We'll cover this as part of that fix

**Comment by ramonsmits** [comment]
I like that approach, but important for me is that it reports all possible locations during startup and also shows the license information no matter it the license is valid or expired.

We could add that to #629 then this issue can be closed but I would keep them separate. This is about informing the other about the scanning behavior.

**Comment by gbiellem** [comment]
@ramonsmits :+1: I didn't close the issue because I agree they are two separate issues.  Just wanted you to be aware there is a fix in the works that would address this so we didn't duplicate effort

**Comment by dvdstelt** [comment]
It would also be awesome to keep the found license in-memory, but if it expired, keep on searching for newer licenses.

I noticed it first searches on disk and then through the registry. If for example, it finds a license on disk but this one is expired, continue the search for a possible newer license in the registry. I had this issue multiple times before when upgrading a license, that an older license was found first. Just updating to a newer license didn't work, because of this. And of course as @ramonsmits pointed out, log every location that is being searched.

**Comment by gbiellem** [comment]
Implemented in 1.14
