### ISSUE TITLE
Button in management tool to open log file

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#675]
The path where the log files are stored is clickable but having a button that directly opens the default log file location (before rotation) would help to quickly open the log.

**Comment by gbiellem** [comment]
@sergioc any suggestion on the layout if we add a button for this?

**Comment by sergioc** [comment]
I see two options:


#### Option 1

Show an icon next to "Log path":

![screenshot 2016-02-19 09 21 02](https://cloud.githubusercontent.com/assets/493451/13164816/b7f3f150-d6ea-11e5-96e1-e9b42a00bf56.png)

(On hover it shows the icon label):

![screenshot 2016-02-19 09 22 05](https://cloud.githubusercontent.com/assets/493451/13164822/c64f712a-d6ea-11e5-8e0e-11b81b7af630.png)

#### Option 2

Show it next to the main instance actions (accessing the log file seems significant enough to place it there):

![screenshot 2016-02-19 09 24 55](https://cloud.githubusercontent.com/assets/493451/13164853/ec3c0a7e-d6ea-11e5-86a2-83328d2a219b.png)

**Comment by johnsimons** [comment]
I'm confused, what is wrong with opening the folder and opening the file u are after ?

**Comment by sergioc** [comment]
@johnsimons: @ramon is requesting to have the possibility to open the file in one click for quicker access.

**Comment by johnsimons** [comment]
I get that @sergioc, and I am asking whether do we really need it, is it that slow to open a folder and double click a file?

**Comment by sergioc** [comment]
> is it that slow to open a folder and double click a file?

If @ramonsmits is making the feature request, it probably is within the use case he presented.

What would be the problem of adding the shortcut?

**Comment by johnsimons** [comment]
@sergioc as part of my role as maintainer of this repo, I get to triage feature requests, at the moment I don't really see a strong compelling reason to go ahead with the feature request, because there is a viable option to achieve the end result.

What do the other @Particular/servicecontrol-maintainers think ?

And yes I know it is an easy thing to do, but that does not mean we should just go ahead and do it.

**Comment by gbiellem** [comment]
Im on the fence. I don't see a compelling use case to do it but i don't
have any objection to someone putting it in. I feel it would be a very pow
prio

**Comment by mikeminutillo** [comment]
Do customers ever want to look at the logs without us asking them to? Probably not. Either it's working or it's not. If it's not it's likely they are talking to us about it and we are saying "send us the logs". To do that, they'll need the folder.

We just implemented a feature to roll the logs at 30MB to prevent massive log files. That means that, at any given moment when I'm about to open the log, it may have just rolled over and the info I am looking for is not in the latest file. Instead of closing a file and opening the next one I now need to open the folder anyway, then figure out which one I was just looking at and which one is next.

For those reasons, I am :-1:

**Comment by sergioc** [comment]
@mikeminutillo :+1: that's a solid argument against.

@ramonsmits thoughts?

**Comment by mauroservienti** [comment]
I'm :-1: as well

**Comment by johnsimons** [comment]
IMHO, I would much prefer to have a button that emails us everything, eg zip all logs and send it to us

**Comment by gbiellem** [comment]
@johnsimons - 

Email :-1:  - remember in prod this is running on a server which probably won't allow it

I'm also meh about zipping... It's built into the OS these days so why bother duplicating an OOTB feature. Also I've never heard from a customer that they had an issue zipping our logs

**Comment by gbiellem** [comment]
@johnsimons  if it was more that zipping - say a button which also gathered stats about the PC and included that then i'd be more enthusiastic. (e.g disk layout, ram, proc type(s). version of SC, version of transport in use,  running services  etc  )  This would also cut down on the questions we have to go back to customer with

**Comment by johnsimons** [comment]
@gbiellem I guess the button could create a zip with everything we need to analyse the issue, how they send that to us, is up to them

**Comment by gbiellem** [comment]
We are probably getting off topic now though - That's more a "generate support request" type thing than a "View" log button.  @johnsimons  if you want to pursue this I'd say we open another issue and based on the number of :-1:  here close this one
