### ISSUE TITLE
Improve SC performance

### ISSUE THREAD

**Issue by pablocastilla** [Particular/ServiceControl#685]
Hi!

I see that SC should perform better. In my scenario with lots of messages I have to create several SC to make it work because it can not process auditing messages in a reasonable time.

I have read in the google group that the problem is because of the raven embedded db and you will change it. 

I think SC should write to a scalable database, maybe one scalable free NoSQL. Or use some NHibernate adapter if you will use a relational one, with a guide for good database indexing. I use NSB under Oracle and I think my client wouldn't like to pay for a SQL Server and I doubt the express would perform well.

Just my 2 cents

**Comment by johnsimons** [comment]
Hi @pablocastilla,

Thanks a lot for your insight into SC performance.
Yes we are very aware of the performance issues that SC currently suffers from, we are constantly trying to improve it, and yes we are also looking at alternative data stores.
One thing we are currently doing is componentize SC into more granular capabilities and this capailities may use different storages based on their own independent requirements.

So with all this in mind, thanks a lot for sharing your thougths on this and I will close this issue for now, since is already cover in our redevelopment plans.
