### ISSUE TITLE
Error and audit queue names are enforced when not required

### ISSUE THREAD

**Issue by adamralph** [Particular/ServiceControl#849]
When creating a new instance, I'm forced to enter queue names for error forwarding and audit forwarding even though I'm leaving those options off.

Normally, I wouldn't care, but when I was adding a second SC instance (for testing a change in SI) I had to manually edit it them because they clashed with the existing instance.

Would it be possible to make to so that those queue names can be omitted/ignored if error forwarding and audit forwarding are switched off?

**Comment by gbiellem** [comment]
The historical reason for this working this way is that if the queue isn't created as setup time then toggling the setting from off to on directly via an app.config will result in an error and the service won't start and
we don't create the queues on demand at service startup as there is no guarantee the service account has the rights to do so.

If these setting were not exposed via app config I'd be 👍 for changing this.  Otherwise I'm 👎

**Comment by johnsimons** [comment]
@gbiellem given that we want everyone to not update the config file manually but instead go via  management tool, should we rethink this and actually let it fail ?

**Comment by gbiellem** [comment]
@johnsimons If you're suggesting pulling those settings out of app.config and storing them elsewhere (maybe in the DB) then I'd be all for changing this to the behavior @adamralph has suggested

**Comment by johnsimons** [comment]
> If you're suggesting pulling those settings out of app.config and storing them elsewhere

no I am not suggesting that.

All I am saying is that even thought users can manually update the config file and make changes that would break ServiceControl, we are not really gaining much for enforcing Error and audit queue names even when we are turning them off, eg, if user decides to change the forwarding queues to something else manually, they would break it since the queues do not exist.

So I am for removing this enforcement and let the system fail to start if they decide to manually turn it on, instead of using the management tool.

**Comment by gbiellem** [comment]
@johnsimons  and I got on a zoom call and discussed this further.  He has won me over so now I'm 👍 for modifying this to the behavior outlined by @adamralph and leaving the setting in the app.config for the time being. Removing those should be a separate exercise.  I'll put together a PR

**Comment by gbiellem** [comment]
Implemented in #852
