### ISSUE TITLE
Edit instance does not create required forwarding queue

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#874]
Affects Servicecontrol 1.29 and 1.30 only

To repro:

 - Create an instance with the forwarding queues off
 - Edit the instance and turn on the forwarding feature and specify a new queue name
-  Save the changes

This will result in the ServiceControl instance not starting and the logs indicating the forwarding queue does not exist.

**Comment by manuelsalvatori** [comment]
Hi @gbiellem 
actually something similar append to me, I created a brand new Instance setting the forwarding for both audit and error, and I just noticed this morning that the error forwarding was set off. I edited the configuration, saved, ServiceControl (1.29) restarted and now I can see it correctly configured but as yours, neither my instance is starting.

Odd thing, a second instance created at the same time was setup correctly with bot forwardings, but after trying to edit it, the forwarding is disappearded for the error queue after an update validation error (ref [#873](https://github.com/Particular/ServiceControl/issues/873).

**Comment by gbiellem** [comment]
@manuelsalvatori  

yes I noticed this while trying to repro the validation issue you raise (#873)  - Suspect they are linked.  I'll try and fix both of them quickly and get a release ASAP

**Comment by manuelsalvatori** [comment]
Cool thanks, it is not a show stopper for me right now.
And completely off topic, just a suggestion for a better usability (personal preference).
When you click on "Advanced options" of any instance and you go back to the main view, I get the message "There are no ServiceControl instances configured", it is not actually right and in fact clicking on the refresh button I get my instances back listed.

I know this is not related but I think that could be a quick fix to do, just triggering the refresh when going back to the view (if this is not the expected behaviour).

**Comment by gbiellem** [comment]
@manuelsalvatori thanks for letting us know about the refresh. I'll open a seperate  issue for that and look into it.
