### ISSUE TITLE
ServiceControl returns empty string on null values

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceControl#889]
We need to display null values on ServiceInsight but the property value returned is an empty string. We won't be able to distinguish between an empty string vs. a null (or lack of value).

**Comment by boblangley** [comment]
@HEskandari Is this SagaAudit or message header data? or something else...

**Comment by HEskandari** [comment]
@boblangley AFAIR this is across the board. A brief conversation at Lisbon with one of the maintainers (think @mikeminutillo) suggested that this has something to do with the Json serializer of choice. The way this was revealed was through the Saga Audit data in SI where a nullable property of type DateTime was sent as empty string instead of Null.

**Comment by WilliamBZA** [comment]
We should be able to tweak the serialization to drop the null values instead of sending an empty string. I feel like if we apply a global change though that this needs a large amount of investigation and testing before we make the change. There's a lot of deserialization going on between SP and SI and I'm not entirely sure how much will break if we change the global settings.

http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_NullValueHandling.htm

**Comment by HEskandari** [comment]
I spent some time verifying this. Let me elaborate and I think we can change the issue title/description to reflect this.

This was raised because of how Saga Audit works. Saga Audit captures the 'changes' made to saga data. Those changes are captures as serialized json version of saga data (plus a few other attributes like status, start and finish time, etc. which is not related to the issue).

The problem is that the serialized json is stored as string and has no type information and on SI there's no way to find out what the actual type is and everything is considered to be a string. This makes things difficult:

 - What's the underlying type? is it a string, or a guid?
 - Is a 'Null' value an actual null string or empty string? or is it some other data type where the data was missing?

Note that there is a "$type" information in the stored json, but since we don't have access to the assembly/type information, we can not deserialize the string as that object. 

I have attached a sample json payload of what I get from SC. Please note how *NullDate* property is serialized where the property is of type Nullable<DateTime>.

[json.txt](https://github.com/Particular/ServiceControl/files/744354/json.txt)

**Comment by boblangley** [comment]
The way we serialize saga data a `Nullable` type (including `string`) will report `null` for the value. An empty string will have an empty string value `""` not `null`.

Perhaps this is a problem with a specific version of the Saga Audit plugin?

**Comment by mikeminutillo** [comment]
@HEskandari what is the next step with this one?

**Comment by HEskandari** [comment]
I'm happy to send a repro, if it helps?

**Comment by mikeminutillo** [comment]
Worked with @HEskandari today to repro this. We confirmed that nulls and empty strings are treated differently:
- By the Saga Audit plugin
- On the wire between Saga Audit and SC
- In the Raven Database after ingestion
- On the wire between SC and SI

This issue is [here](https://github.com/Particular/ServiceInsight/blob/master/src/ServiceInsight/Saga/JsonPropertiesHelper.cs#L13) in SI where the null is being explicitly converted into an empty string. As this is not happening in SC (or the SagaAudit plugin) I will close this issue.
