### ISSUE TITLE
Upgrade fails because files still in use

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#907]
In Raygun we have several reports of exceptions when upgrading ServiceControl instances. In each case it look like the existing service has not completely shutdown and the old files are locked.  This exhibits itself as the following exception:

'Access to the path 'C:\Program Files (x86)\Particular Software\ServiceControl\Autofac.dll' is denied.'

**Comment by gbiellem** [comment]
Unfortunately the raygun information doesn't include the old version just the version that SC is moving to.  So not sure if this is a general problem or specific to an old version

**Comment by fourpastmidnight** [comment]
## Introduction

I'm running into this, too. 

We've tried several attempts and all of them have resulted in deployment failures in our production test environment, except the last attempt, which we plan on testing in the upcoming days but which I think will finally be successful.

## First Attempt

The deployment script I wrote contains some code to explicitly stop the ServiceControl service. (I didn't want `Invoke-ServiceControlInstanceUpgrade` to do this for me because I didn't want the instance restarted right away after the upgrade.) Immediately after stopping the ServiceControl service, I call `Invoke-ServiceControlInstanceUpgrade`. This failed per the same error message @gbiellem mentions.

## Second Attempt

My next attempt was to let `Invoke-ServiceControlInstanceUpgrade` manage the stopping of ServiceControl anyway, despite my desire to not let it do so. However, this resulted in the same issue.

## Third Attempt

The third attempt was to once again stop ServiceControl myself and run a busy-wait loop, with a timeout, waiting for the ServiceControl service to stop. However, this final mitigation also failed--within 20s!--with the same error!! So, Windows is reporting the ServiceControl service as stopped, but something still has a file lock on Autofac.dll. It must be ServiceControl itself; it still must be running even though the service is being reported as stopped. Which leads to the last attempt....

## Fourth Attempt and Final Resolution (still under test, though)

This is still undergoing testing, but I think I found a solution; it's certainly not a desirable solution, but it's the best I could come up with. When ServiceControl has been running for a while and is under load, these attempts above have not worked. On a machine where ServiceControl has not been running long and there's very little data in the database, the attempts above all pass--hence why when we tested, everything seemed to work, but when we released, it blew up.

So the latest attempt changes the wait logic: Wait (with a timeout) to ensure the service is stopped _**AND**_ for the ServiceControl.exe process to no longer be running. (It turns out, [this is the very same check that ServiceContril is already doing!](https://github.com/Particular/ServiceControl/blob/257cf83042fdbea7378d42ef08f5614789da223f/src/ServiceControlInstaller.Engine/Instances/BaseService.cs#L51-L79))

On a machine with very little SC uptime and hardly any data, the service stops in <30ms. However, when timing both the service being stopped and ServiceControl.exe no longer running in memory, it took ~.75s. Quite a difference, and on a system under load, I suspect the difference is even greater. And, it appears, in my environments, this difference in time exceeds 5 seconds. And, no `TimeoutException` is being thrown, because an upgrade attempt is made. Which means the exception is probably expected to occur as a result of line 63 failing to stop the service in 1m or less. 

## Conclusion

Therefore, I've just discovered why this detection logic doesn't work: there appear to be at least two bugs in that detection code:

First, on line 71, `t.Wait(5000)` is called all by itself. This method returns a boolean value. If the task does not complete successfully within the given timeout, the `Task.Wait(int32)` method returns `false`. But the return value of the `Task.Wait(int32)` call is not used.

Second, even if the return value from `t.Wait(5000)` were to be used, it would _always_ return `false` because the task is never completed successfully. [The task delegate is basically a tight-loop testing whether or not the process still exists.](https://github.com/Particular/ServiceControl/blob/257cf83042fdbea7378d42ef08f5614789da223f/src/ServiceControlInstaller.Engine/Instances/BaseService.cs#L64-L70) But the return value of that check (`HasUnderlyingProcessExited`) is never used to complete the task when that check returns `true`. So, when the timeout expires, the task has not completed, and `t.Wait(5000)` would always return `false`.

Third, I found an additional bug while creating a PR to fix the two issues above: in each of the Upgrade() methods for the installers, if the service (and, apparently, the underlying process) is not stopped, an error is logged, but the upgrade method continues on! This may also result in a failed upgrade (or, an error will be logged, but the upgrade could be successful, depending on how things turn out!!).

I would humbly submit that even if this code were written correctly, that 5s may not be enough time to allow for the ServiceControl process to exit in some production environments (as evidenced by my deployment failures over the last 3 or 4 days). Either this timeout limit should be increased, or perhaps it should be configurable--passed in as a parameter to the service (with a suitable default, say 5s as it is currently, or possibly something a bit longer). This way, for those environments where it's known to take longer, better control can be exerted to prevent upgrade failures.

As alluded to above, I'm submitting a PR to fix this issue.

**Comment by dbelcham** [comment]
@fourpastmidnight Thanks for the detailed write up and the PR. I'm gathering info so we can triage and prioritize this work.

It reads like you're trying to upgrade your ServiceControl instances when this happens. Is that the case and, if so, is this blocking that upgrade? Do you have a work-around for the problem?

**Comment by fourpastmidnight** [comment]
Yes, that's the case. Is it blocking the upgrade? Yes and no. Ultimately, the upgrade is successful, but the first attempt _always_ fails and a subsequent deployment then completes successfully.

The workaround I put in place is a PowerShell script version of my PR that I run before invoking `Invoke-ServiceControlInstanceUpgrade`, but with a longer timeout for waiting for the process to exit.

**Comment by dbelcham** [comment]
@fourpastmidnight Thanks for that update. We will be looking at adding this to a future release of ServiceControl.
