### ISSUE TITLE
Retry message fails when using a Multi Schema SQL Transport

### ISSUE THREAD

**Issue by rubenmamo** [Particular/ServiceControl#935]
I'm having problems with getting service control to work correctly when using a multi-schema SQL Server transport.

My PC is named MT7N001-001
Service Control Instance is named RubenDevelopmentServiceControl

My transport setup is as follows:
2 Schemas:
* Common
* HumanResources

The Common Schema has the following tables:
* Audit
* AuditArchive
* Error
* RubenDevelopmentServiceControl
* RubenDevelopmentServiceControl.Errors
* RubenDevelopmentServiceControl.MT7N001-001
* RubenDevelopmentServiceControl.staging

The HumanResources Schema has the following tables:
* Company.HumanResources.ADConnector
* Company.HumanResources.ADConnector.MT7N001-001
* Company.HumanResources.ADConnector.Retries
* Company.HumanResources.ADConnector.Timeouts
* Company.HumanResources.ADConnector.TimeoutsDispatcher

Service Control is setup using this connection string: Data Source=.\sqlexpress;Initial Catalog=ServiceBus;MultipleActiveResultSets=True;Application Name=Service Control;Integrated Security=True;Queue Schema=Common;
Below is the full configuration of service control:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <appSettings>
        <add key="Raven/Esent/MaxVerPages" value="2048" />
        <add key="ServiceControl/DBPath" value="C:\ProgramData\Particular\ServiceControl\RubenDevelopmentServiceControl\DB" />
        <add key="ServiceControl/TransportType" value="NServiceBus.SqlServerTransport, NServiceBus.Transports.SQLServer" />
        <add key="ServiceControl/HostName" value="localhost" />
        <add key="ServiceControl/Port" value="33333" />
        <add key="ServiceControl/LogPath" value="C:\ProgramData\Particular\ServiceControl\RubenDevelopmentServiceControl\Logs" />
        <add key="ServiceControl/ForwardAuditMessages" value="False" />
        <add key="ServiceControl/ForwardErrorMessages" value="False" />
        <add key="ServiceControl/AuditRetentionPeriod" value="30.00:00:00" />
        <add key="ServiceControl/ErrorRetentionPeriod" value="15.00:00:00" />
        <add key="ServiceBus/AuditQueue" value="Audit" />
        <add key="ServiceBus/ErrorQueue" value="Error" />
    </appSettings>
    <connectionStrings>
        <add name="NServiceBus/Transport" connectionString="Data Source=.\sqlexpress;Initial Catalog=ServiceBus;MultipleActiveResultSets=True;Application Name=Service Control;Integrated Security=True;Queue Schema=Common;" />
    </connectionStrings>
    <runtime>
        <gcServer enabled="true" />
    </runtime>
</configuration>
```
The transport in the windows service is setup as follows:
```
transportConfiguration.UseSchemaForEndpoint("Company.HumanResources.ADConnector", "HumanResources");
```

I had a failed message and when I submitted it for retry the following appeared in the events in the dashboard of service pulse
```
'8f2556e6-efac-7bf4-2157-ef57c1f9feb2' failed to be submitted for retry to 'Company.HumanResources.ADConnector.Timeouts@[HumanResources]'. Reason for failure: Invalid object name 'Common.Company.HumanResources.ADConnector.Timeouts'.
```

For some reason ServicePulse or ServiceControl is adding the Common schema at the front of the table name instead of using HumanResources as specified in the source name.

I'm not sure whether this is a configuration issue or a bug in ServiceControl as I couldn't find documentation on how to use it.

**Comment by rubenmamo** [comment]
p.s. I'm currently running ServicePulse v1.8.4 and ServiceControl v1.38.0

**Comment by SzymonPobiega** [comment]
Hi Ruben

I am assuming your endpoints use NServiceBus 6. Is that correct?
ServiceControl is still based on Version 5 of NServiceBus. This is why even
though Version 6 adds the schema name to the queue name in the address e.g.
Company.HumanResources.ADConnector@[HumanResources], ServiceControl drops
the part after @ when parsing the address.

Since your SC configuration uses "Queue Schema=Common" in the connection
string, SC defaults to sending all messages to the common schema, also the
retries. In order to mitigate this problem, you need to add per-destination
configuration as described here
https://docs.particular.net/nservicebus/sqlserver/connection-settings?version=sqlserver_2#custom-schema-per-destination
e.g. in your case:

<connectionStrings>
<add name="NServiceBus/Transport" connectionString="Data
Source=.\sqlexpress;Initial
Catalog=ServiceBus;MultipleActiveResultSets=True;Application Name=Service
Control;Integrated Security=True;Queue Schema=Common;" /> //Default for SC
<add name="NServiceBus/Transport/Company.HumanResources.ADConnector"
connectionString="Data Source=.\sqlexpress;Initial
Catalog=ServiceBus;MultipleActiveResultSets=True;Application Name=Service
Control;Integrated Security=True;Queue Schema=HumanResources;" /> //Default
for SC
</connectionStrings>

Unfortunately currently you need to add named connection string for each
endpoint managed by this instance of ServiceControl. We're working on
solving this issue in a more elegant way in future versions of
ServiceControl.

Hope it helps,
Szymon


2017-03-16 10:52 GMT+01:00 Ruben Mamo <notifications@github.com>:

**Comment by rubenmamo** [comment]
Hi Szymon,

Thank you for your prompt reply. Yes I am using NServiceBus 6.

I added the connection strings as instructed, however I started getting slightly different errors.

Just in case anyone else has this issue, you need to add 3 additional connection strings to the service control config since the override is per queue and not per endpoint. The additional two are for the Timeouts queue and the TimeoutsDispatcher queue. See updated config below:

```
<add name="NServiceBus/Transport" connectionString="Data Source=.\sqlexpress;Initial Catalog=ServiceBus;MultipleActiveResultSets=True;Application Name=Service Control;Integrated Security=True;Queue Schema=Common;" />
<add name="NServiceBus/Transport/Company.HumanResources.ADConnector" connectionString="Data Source=.\sqlexpress;Initial Catalog=ServiceBus;MultipleActiveResultSets=True;Application Name=Service Control;Integrated Security=True;Queue Schema=HumanResources;" />
<add name="NServiceBus/Transport/Company.HumanResources.ADConnector.Timeouts" connectionString="Data Source=.\sqlexpress;Initial Catalog=ServiceBus;MultipleActiveResultSets=True;Application Name=Service Control;Integrated Security=True;Queue Schema=HumanResources;" />
<add name="NServiceBus/Transport/Company.HumanResources.ADConnector.TimeoutsDispatcher" connectionString="Data Source=.\sqlexpress;Initial Catalog=ServiceBus;MultipleActiveResultSets=True;Application Name=Service Control;Integrated Security=True;Queue Schema=HumanResources;" />
```

Is there a plan for when Service Control is updated to user NServiceBus 6 to solve this issue?

Ruben

**Comment by SzymonPobiega** [comment]
@rubenmamo we're working on this issue. It is likely that the end solution will not be just upgrading SC to NServiceBus 6 as this would not solve other related issue.

In the meantime you can also use a community transport adapter https://github.com/SzymonPobiega/ServiceControl.TransportAdapter that allows you to run ServiceControl on a different transport than your endpoints. In you case you can actually run SQL transport on both sides. Because the adapter runs on NServiceBus 6, it understands the concept of schema and will solve the routing problem without the need to configure every single queue.

**Comment by SzymonPobiega** [comment]
@rubenmamo did you have a change to look at the transport adapter?

**Comment by rubenmamo** [comment]
@SzymonPobiega I haven't had a chance to look into it yet. I will try to find some time next week

**Comment by SzymonPobiega** [comment]
@rubenmamo OK. Let me know if you need any help with it.

**Comment by markgould** [comment]
@SzymonPobiega This is pretty neat. So does this get added to each endpoint? Just trying to understand exactly how the architecture works.

One minor note, the documentation reads RabbitMQ -> MSMQ but the code is really SQL -> MSMQ.

**Comment by SzymonPobiega** [comment]
@markgould thanks. I'll fix it. No, it does not need to be added to each endpoint. In a multi-instance topology you need one adapter per SQL server instance. Unless obviously each instance uses it's own DB for queues but we usually don't recommend such topology.

**Comment by SzymonPobiega** [comment]
@markgould @rubenmamo With SC V3 we upgraded to NServiceBus 7 which means that SC will correctly interpret multi-schema and multi-catalog addresses and will be able to retry these messages to correct queues.
